import sys
from PIL import Image

def to_hex(byte_data):
    """Formats bytes as hex pairs with spacing."""
    hex_str = ""
    for i, b in enumerate(byte_data):
        if i % 16 == 0:
            hex_str += "\n\t\t\t"
        hex_str += f"0x{b:02X}, "
    return hex_str.rstrip(", ")

def create_icn_hash(img_32):
    """Creates ICN# (32x32 1-bit bitmap + mask) data."""
    # Convert to 1-bit (dithered/thresholded)
    bw = img_32.convert("1")
    mask = img_32.split()[3].convert("1") # Alpha channel as mask
    
    bitmap_data = bytearray()
    mask_data = bytearray()
    
    # Pack bits
    for y in range(32):
        row_bits = 0
        row_mask = 0
        for x in range(32):
            pixel = bw.getpixel((x, y))
            # 1 = black in PIL '1' mode usually means non-zero, but Mac is 1=black?
            # Actually standard binary: 1=black(foreground), 0=white(background).
            # PIL '1': 0=black, 255=white. Wait.
            # Let's check PIL conversion. 
            # If (0,0,0) -> 0. (255,255,255) -> 255 (if using point).
            # Standard mac icon: 1=black.
            
            p_val = 1 if pixel == 0 else 0 # Invert for Mac (assuming PIL 0=black)
            
            # Mask: 1=opaque
            m_val = 1 if mask.getpixel((x, y)) > 127 else 0
            
            row_bits = (row_bits << 1) | p_val
            row_mask = (row_mask << 1) | m_val
        
        bitmap_data.extend(row_bits.to_bytes(4, 'big'))
        mask_data.extend(row_mask.to_bytes(4, 'big'))
        
    return bitmap_data + mask_data

def create_icl8(img_32):
    """Creates icl8 (32x32 8-bit indexed) data."""
    # Convert to P mode (palette) using standard Mac OS palette if possible, 
    # but for now we'll let PIL quantize to 256 colors. 
    # Ideally we'd map to the standard system palette, but custom palette MIGHT work 
    # if clut is provided, but icl8 usually assumes system palette.
    # We will assume a standard quantization for now.
    
    # Simulating Mac System Palette (approximate) is hard without the CLUT.
    # We'll just quantize to 256 colors. It might look slightly off if OS forces system palette.
    # Better approach: 
    # Using 'P' mode.
    
    indexed = img_32.convert("P", palette=Image.ADAPTIVE, colors=256)
    return indexed.tobytes()

def create_ics_hash(img_16):
    """Creates ics# (16x16 1-bit bitmap + mask) data."""
    bw = img_16.convert("1")
    mask = img_16.split()[3].convert("1")
    
    bitmap_data = bytearray()
    mask_data = bytearray()
    
    for y in range(16):
        row_bits = 0
        row_mask = 0
        for x in range(16):
            p_val = 1 if bw.getpixel((x, y)) == 0 else 0
            m_val = 1 if mask.getpixel((x, y)) > 127 else 0
            
            row_bits = (row_bits << 1) | p_val
            row_mask = (row_mask << 1) | m_val
            
        bitmap_data.extend(row_bits.to_bytes(2, 'big'))
        mask_data.extend(row_mask.to_bytes(2, 'big'))
        
    return bitmap_data + mask_data

def create_ics8(img_16):
    """Creates ics8 (16x16 8-bit indexed) data."""
    indexed = img_16.convert("P", palette=Image.ADAPTIVE, colors=256)
    return indexed.tobytes()

def to_hex_string(byte_data):
    """Formats bytes as a Rez hex string (e.g. $'0011...')."""
    # Break into lines of 32 bytes for readability
    hex_str = "$\""
    for i, b in enumerate(byte_data):
        if i > 0 and i % 32 == 0:
            hex_str += "\"\n\t\t\t$\""
        hex_str += f"{b:02X}"
    hex_str += "\""
    return hex_str

def main():
    if len(sys.argv) < 3:
        print("Usage: generate_icon_r.py <32x32.png> <16x16.png>")
        sys.exit(1)
        
    img_32 = Image.open(sys.argv[1]).resize((32,32))
    img_16 = Image.open(sys.argv[2]).resize((16,16))
    
    icn_hash = create_icn_hash(img_32)
    icl8_data = create_icl8(img_32)
    ics_hash = create_ics_hash(img_16)
    ics8_data = create_ics8(img_16)
    
    print("/* Quake 3 Icon Resources generated by Python */")
    print("/* Signature: Q3A */")
    
    # BNDL Resource (Template based, usually safe if string format matches)
    # But let's check standard BNDL format. 
    # resource 'BNDL' { TypeName; ID; array { TypeName; LocalID; } ... }
    # My previous BNDL looked okay-ish but relied on standard templates.
    # To be safe, let's keep the BNDL as a resource if it works, or convert to data if needed.
    # The previous error was on ICN# lines (line 41+). The BNDL seemed to parse? 
    # Actually, let's stick to resource for BNDL and FREF as they are text-heavy.
    
    print("""
resource 'BNDL' (128) {
	'Q3A ',
	0,
	{
		'ICN#',
		{
			0, 128
		},
		'FREF',
		{
			0, 128
		}
	}
};

resource 'FREF' (128) {
	'APPL',
	0,
	""
};
""")
    
    # Icons - Use raw data to avoid template mismatch
    print(f"data 'ICN#' (128, \"Quake3\") {{ \n\t{to_hex_string(icn_hash)} \n}};")
    print(f"data 'ics#' (128, \"Quake3\") {{ \n\t{to_hex_string(ics_hash)} \n}};")
    
    # 8-bit Color Icons
    print(f"data 'icl8' (128, \"Quake3\") {{ \n\t{to_hex_string(icl8_data)} \n}};")
    print(f"data 'ics8' (128, \"Quake3\") {{ \n\t{to_hex_string(ics8_data)} \n}};")

if __name__ == "__main__":
    main()
