/* Actual item factory, structure/parser bodies and engine allocator metadata. */
#include Q3_ITEM_CONFIG_SOURCE
#ifndef Q3_ITEM_NATIVE_INTERFACE
botlib_import_t botimport;
botlib_globals_t botlibglobals;
#endif
extern int numtokens;
static void *heap[64],*hunk[16],*heapRaw[64],*hunkRaw[16];
static unsigned long engineOffset;
static int heapLive,hunkLive,requests,failAt,errors,warnings,messages,opens,closes;
static int lengths[256];
static const char *fileText;
static void Check(int condition,const char *message){if(!condition){fprintf(stderr,"Item configuration regression failed: %s\n",message);exit(1);}}
static void *Allocate(int size,int arena){void **slots=arena?hunk:heap;int cap=arena?16:64,i;Check(size>0&&requests<256,"signed complete native allocation request");lengths[requests++]=size;if(requests==failAt||size>1048576)return NULL;for(i=0;i<cap;i++)if(!slots[i]){void *raw=malloc((size_t)size+engineOffset);Check(raw!=NULL,"physical native storage");slots[i]=(char *)raw+engineOffset;if(arena)hunkRaw[i]=raw;else heapRaw[i]=raw;if(arena)hunkLive++;else heapLive++;return slots[i];}Check(0,"bounded physical native owners");return NULL;}
static void *HeapAlloc(int size){return Allocate(size,0);}
static void *HunkAlloc(int size){return Allocate(size,1);}
static void HeapFree(void *pointer){int i;for(i=0;i<64;i++)if(heap[i]==pointer){free(heapRaw[i]);heapRaw[i]=NULL;heap[i]=NULL;heapLive--;return;}Check(0,"only native physical heap storage frees through callback");}
#ifndef Com_Memset
void Com_Memset(void *out,int value,size_t size){memset(out,value,size);}
#endif
#ifndef Com_Memcpy
void Com_Memcpy(void *out,const void *in,size_t size){memcpy(out,in,size);}
#endif
void QDECL Com_Error(int level,const char *format,...){(void)format;Check(failAt&&requests==failAt&&level==ERR_FATAL,"only expected nullable parser allocation fatal");}
void QDECL Com_Printf(const char *format,...){(void)format;}
void QDECL Log_Write(char *format,...){(void)format;}
static void QDECL Print(int level,char *format,...){(void)format;if(level==PRT_ERROR||level==PRT_FATAL)errors++;else if(level==PRT_WARNING)warnings++;else{Check(level==PRT_MESSAGE,"native item severity");messages++;}}
static int Open(const char *path,fileHandle_t *file,fsMode_t mode){Check(mode==FS_READ&&strlen(path)<MAX_QPATH,"fitting native VFS path");opens++;*file=1;return (int)strlen(fileText);}
static int Read(void *out,int length,fileHandle_t file){Check(file==1&&length==(int)strlen(fileText),"complete actual file read");memcpy(out,fileText,length);return length;}
static int Seek(fileHandle_t file,long offset,int origin){Check(file==1&&offset==0&&origin==FS_SEEK_CUR,"native exact-length VFS interval");return 0;}
static void Close(fileHandle_t file){Check(file==1,"native file closes");closes++;}
static const char *nativeText="iteminfo \"weapon_native\" { name \"Native\" model \"models/native.md3\" modelindex 7 type 2 index 42 respawntime 12.5 mins {-1,-2,-3} maxs {1,2,3} }\n";
static void Attempt(const char *text){fileText=text;requests=failAt=errors=warnings=messages=opens=closes=0;memset(lengths,0,sizeof(lengths));}
static void Begin(void){void *probe;unsigned long prefix;Check(!heapLive&&!hunkLive&&!numtokens,"prior parser/engine arenas reset");Attempt(nativeText);botimport.GetMemory=HeapAlloc;botimport.HunkAlloc=HunkAlloc;botimport.FreeMemory=HeapFree;botimport.Print=Print;botimport.FS_FOpenFile=Open;botimport.FS_Read=Read;botimport.FS_FCloseFile=Close;botimport.FS_Seek=Seek;engineOffset=0;probe=GetMemory(0);Check(probe&&heapLive==1,"measure actual native ownership prefix");prefix=(char *)probe-(char *)heap[0];FreeMemory(probe);engineOffset=(__alignof__(script_t)-prefix%__alignof__(script_t))%__alignof__(script_t);Attempt(nativeText);}
static void End(void){int i;LibVarDeAllocAll();Check(!heapLive&&!numtokens,"actual source/queue/cache/staging heap owners physically release");for(i=0;i<16;i++)if(hunk[i]){free(hunkRaw[i]);hunkRaw[i]=NULL;hunk[i]=NULL;hunkLive--;}Check(!hunkLive,"owning engine resets physical hunk arena");}
static void Values(itemconfig_t *config){iteminfo_t *item;Check(config&&config->numiteminfo==1&&config->iteminfo==(iteminfo_t *)((char *)config+sizeof(itemconfig_t)),"one complete native item and rebased inline pointer");item=config->iteminfo;Check(!strcmp(item->classname,"weapon_native")&&!strcmp(item->name,"Native")&&!strcmp(item->model,"models/native.md3")&&item->modelindex==7&&item->type==2&&item->index==42&&item->respawntime==12.5f&&item->number==0&&item->mins[0]==-1&&item->mins[1]==-2&&item->mins[2]==-3&&item->maxs[0]==1&&item->maxs[1]==2&&item->maxs[2]==3,"actual native structure fields remain");}

static void Golden(void){itemconfig_t *config;Begin();config=LoadItemConfig("native.c");Values(config);Check(opens==1&&closes==1&&!errors&&!warnings&&messages==1&&heapLive==2&&hunkLive==1&&!numtokens,"native config source releases before publication with shared cache only");FreeMemory(config);End();}
static void Malformed(const char *text){Begin();Attempt(text);Check(!LoadItemConfig("native.c")&&opens==1&&closes==1&&errors>0&&!messages&&heapLive==2&&!hunkLive&&!numtokens,"malformed item prefix rejects with complete source/staging cleanup and no physical hunk consumption");End();}
static void Nullable(int position){int count;itemconfig_t *config;Begin();config=LoadItemConfig("native.c");Values(config);count=requests;FreeMemory(config);End();Check(position>=1&&position<=count,"known actual nullable stage");Begin();failAt=position;Check(!LoadItemConfig("native.c")&&requests>=failAt&&errors>0&&!messages&&!hunkLive&&!numtokens&&closes==opens,"every nullable import rejects and releases all partial source/staging owners");Check(heapLive==(position>2?2:0),"only complete native count variable survives failed import");Attempt(nativeText);config=LoadItemConfig("native.c");Values(config);FreeMemory(config);End();}
static float Opaque(unsigned int bits){volatile unsigned int representation=bits;unsigned int copy=representation;float value;memcpy(&value,&copy,sizeof(value));return value;}
static void InvalidCount(unsigned int bits){libvar_t *variable;int imports;Begin();variable=LibVar("max_iteminfo","256");Check(variable!=NULL,"invalid native count cache prepares");variable->value=Opaque(bits);imports=requests;Check(!LoadItemConfig("native.c")&&requests==imports&&!opens&&!hunkLive&&heapLive==2&&errors==1,"nonfinite/oversized native count rejects before integer conversion and VFS/arena imports");End();}
static void InvalidPath(int kind){char path[MAX_PATH+1];Begin();memset(path,'x',sizeof(path));path[sizeof(path)-1]=0;Check(!LoadItemConfig(kind==0?NULL:kind==1?"":path)&&!requests&&!opens&&!heapLive&&!hunkLive&&errors==1,"invalid full filename rejects before cache/VFS/arena imports");End();}
static void NativeCounts(void){itemconfig_t *config;libvar_t *variable;int i;char *counts[]={"2.75","0.5","-0.5","-1"};for(i=0;i<4;i++){Begin();variable=LibVar("max_iteminfo",counts[i]);Check(variable!=NULL,"native count cache prepares");if(i>=2)variable->value=Opaque(i==2?0xbf000000U:0xbf800000U);if(i==1||i==2)Attempt("");config=LoadItemConfig("native.c");Check(config!=NULL,"native zero/fractional/negative fallback count retains valid behavior");if(i==1||i==2)Check(!config->numiteminfo&&warnings==1&&!errors,"native zero capacity accepts empty config with warning");else Values(config);Check(errors==(i==3)&&variable->value==(i==3?256.0f:i==0?2.75f:i==1?0.5f:-0.5f),"native negative fallback and fractional cache values remain");FreeMemory(config);End();}}
static void FallbackFailure(void){libvar_t *variable;char *prior;itemconfig_t *config;Begin();variable=LibVar("max_iteminfo","1");Check(variable!=NULL,"complete fallback variable prepares");variable->value=Opaque(0xbf800000U);prior=variable->string;failAt=requests+1;Check(!LoadItemConfig("native.c")&&requests==failAt&&!opens&&!hunkLive&&heapLive==2&&variable->string==prior&&!strcmp(prior,"1")&&variable->value==-1,"nullable native fallback update preserves prior cache and stops before VFS/arena");Attempt(nativeText);config=LoadItemConfig("native.c");Values(config);Check(variable->value==256.0f,"failed native fallback retries");FreeMemory(config);End();}
static void PriorFailure(void){itemconfig_t *prior;iteminfo_t saved;itemconfig_t header;Begin();prior=LoadItemConfig("native.c");Values(prior);saved=prior->iteminfo[0];header=*prior;Attempt("iteminfo");Check(!LoadItemConfig("failed.c")&&hunkLive==1&&heapLive==2&&!numtokens&&!memcmp(&header,prior,sizeof(header))&&!memcmp(&saved,prior->iteminfo,sizeof(saved)),"failed distinct config retains complete prior payload and consumes no extra physical hunk");FreeMemory(prior);End();}
int main(int argc,char **argv){itemconfig_t *config;int i,count;if(argc>1){i=atoi(argv[1]);if(i==0)Malformed("iteminfo");else if(i==1)Malformed("iteminfo \"broken\" { unknown 1 }");else if(i==2){char text[1024];snprintf(text,sizeof(text),"%s#unknown",nativeText);Malformed(text);}else if(i==3){char text[1024];snprintf(text,sizeof(text),"%s\"\\q\"",nativeText);Malformed(text);}else if(i==4)InvalidCount(0x7fc00000U);else if(i==5)InvalidCount(0x4b800000U);else if(i==6)InvalidPath(0);else if(i==7)InvalidPath(2);else{Golden();NativeCounts();}return 0;}Golden();NativeCounts();FallbackFailure();PriorFailure();Malformed("iteminfo");Malformed("iteminfo \"broken\" { unknown 1 }");{char text[1024];snprintf(text,sizeof(text),"%s#unknown",nativeText);Malformed(text);snprintf(text,sizeof(text),"%s\"\\q\"",nativeText);Malformed(text);}for(i=0;i<3;i++)InvalidPath(i);InvalidCount(0x7f800000U);InvalidCount(0xff800000U);InvalidCount(0x7fc00000U);InvalidCount(0x4f000000U);InvalidCount(0xcf800000U);InvalidCount(0x4b800000U);Begin();config=LoadItemConfig("native.c");Values(config);count=requests;FreeMemory(config);End();for(i=1;i<=count;i++)Nullable(i);printf("Real item factory values/counts, %d nullable imports, source rollback and physical heap/hunk ownership passed (issue #48)\n",count);return 0;}
