/* Actual interpolation numeric rollback, equal fallback and variadic log rendering. */
#include <stdarg.h>
static void CaptureLog(char *format,va_list args);
#define Q3_CHARACTER_LOG_HOOK CaptureLog
#define Q3_INTERPOLATION_ENTRY InterpolationFixtureMain
#include "bot_interpolation_regression.c"
#undef Q3_INTERPOLATION_ENTRY
#include <float.h>
static char logText[8192];
static int logActive,logLength;
static void CaptureLog(char *format,va_list args){int length;if(!logActive)return;length=vsnprintf(logText+logLength,sizeof(logText)-(size_t)logLength,format,args);Check(length>=0&&(size_t)length<sizeof(logText)-(size_t)logLength,"complete bounded native variadic log rendering");logLength+=length;}
static float BlendBits(unsigned int bits){volatile unsigned int representation=bits;unsigned int actual=representation;float value;memcpy(&value,&actual,sizeof(value));return value;}
static void BlendSnapshot(void){memcpy(firstSnapshot,botcharacters[1],CHARACTER_BYTES);memcpy(secondSnapshot,botcharacters[2],CHARACTER_BYTES);}
static void EarlyFailure(int mode){int before,second=2;float desired=2.5f;Inputs();if(mode==0)desired=BlendBits(0x7fc00001u);else if(mode==1)botcharacters[1]->skill=BlendBits(0x7fc00001u);else if(mode==2)botcharacters[2]->skill=botcharacters[1]->skill;else if(mode==3)second=1;else if(mode==4){botcharacters[1]->skill=-FLT_MAX;botcharacters[2]->skill=FLT_MAX;}else if(mode==5){botcharacters[1]->skill=FLT_MAX;desired=-FLT_MAX;}else{botcharacters[1]->skill=0;botcharacters[2]->skill=BlendBits(1u);desired=FLT_MAX;}BlendSnapshot();before=requests;{int result=BotInterpolateCharacters(1,second,desired);if(result)fprintf(stderr,"Unexpected interpolation success: mode=%d result=%d desired=%g first=%g second=%g errors=%d\n",mode,result,(double)desired,(double)botcharacters[1]->skill,(double)botcharacters[second]->skill,errors);Check(!result,"invalid desired/endpoint/scale rejects before output publication");}Check(requests==before&&liveOwners==7&&!numtokens&&!botcharacters[3]&&errors==1,"invalid interpolation arithmetic imports nothing and preserves physical inputs");End();}
static void FieldFailure(int mode){int before,index=mode==1||mode==3?78:0;float desired=mode==1?5.0f:2.5f;Inputs();botcharacters[1]->c[index].type=CT_FLOAT;botcharacters[2]->c[index].type=CT_FLOAT;if(mode==0){botcharacters[1]->c[index].value._float=-FLT_MAX;botcharacters[2]->c[index].value._float=FLT_MAX;}else if(mode==1){botcharacters[1]->c[index].value._float=0;botcharacters[2]->c[index].value._float=FLT_MAX;}else{botcharacters[1]->c[index].value._float=BlendBits(mode==2?0x7fc00001u:0x7f800000u);botcharacters[2]->c[index].value._float=1;}BlendSnapshot();before=requests;watchHandle=3;{int result=BotInterpolateCharacters(1,2,desired);watchHandle=0;if(mode==0&&result){unsigned int bits;Com_Memcpy(&bits,&botcharacters[result]->c[0].value._float,sizeof(bits));Check(result==3&&(bits&0x7fffffffu)==0&&!errors&&liveOwners==10&&requests==before+3,"reassociated extreme blend may publish only complete mathematically finite zero");BotFreeCharacter2(result);}else{if(result)fprintf(stderr,"Unexpected field success: mode=%d result=%d value=%g errors=%d\n",mode,result,(double)botcharacters[result]->c[index].value._float,errors);Check(!result,"invalid characteristic/native blend rejects unpublished output");Check(requests==before+(index==78?2:1)&&liveOwners==7&&!numtokens&&!botcharacters[3]&&errors==1,"failed early/late numeric blend frees header and any prior copied string");}}Unchanged();End();}
static void Dump(void){int handle;Inputs();handle=BotInterpolateCharacters(1,2,2.5f);Check(handle==3,"native valid interpolation prepares dump");logLength=0;logText[0]=0;logActive=1;BotDumpCharacter(botcharacters[handle]);logActive=0;Check(strstr(logText,"skill 2.500000\n")&&strstr(logText,"4.250000")&&strstr(logText,"first")&&!errors,"actual dump formats promoted floating skill and native field/string values");BotFreeCharacter2(handle);End();}
static int MissingDefault(const char *path,fileHandle_t *file,fsMode_t mode){if(strstr(path,"default_c.c")){Check(mode==FS_READ,"native missing default lookup mode");opens++;*file=0;return -1;}return Open(path,file,mode);}
static void EqualFallback(void){int handle,i,beforeOwners;unsigned char saved[CHARACTER_BYTES];Reset("skill 1 { 0 1.25 1 11 79 \"one\" }");botimport.FS_FOpenFile=MissingDefault;handle=BotLoadCharacter("bots/native.c",2.5f);Check(handle==1&&botcharacters[handle]->skill==1&&botcharacters[handle]->c[0].value._float==1.25f&&!strcmp(botcharacters[handle]->c[79].value.string,"one"),"missing exact second skill retains first available complete native fallback");for(i=2;i<=MAX_CLIENTS;i++)Check(!botcharacters[i],"equal fallback cannot publish interpolated duplicate");beforeOwners=liveOwners;memcpy(saved,botcharacters[1],CHARACTER_BYTES);Check(BotLoadCharacter("bots/native.c",2.5f)==handle&&liveOwners==beforeOwners&&!memcmp(saved,botcharacters[1],CHARACTER_BYTES)&&!numtokens,"repeated equal fallback retains existing fields and physical owners");BotShutdownCharacters();Check(!liveOwners&&!numtokens,"equal fallback finally physically releases all native owners");}
int main(int argc,char **argv){if(argc>1){int proof=atoi(argv[1]);if(proof<7)EarlyFailure(proof);else if(proof<11)FieldFailure(proof-7);else if(proof==11)EqualFallback();else if(proof==12)Dump();else{InterpolationGolden(1,1);InterpolationGolden(2.5f,1);InterpolationGolden(4,1);InterpolationGolden(5,1);}}else{int mode;for(mode=0;mode<7;mode++)EarlyFailure(mode);for(mode=0;mode<4;mode++)FieldFailure(mode);EqualFallback();Dump();InterpolationGolden(1,1);InterpolationGolden(2.5f,1);InterpolationGolden(4,1);InterpolationGolden(5,1);puts("Real interpolation numeric rollback, native values, equal fallback and floating logs passed (issue #48)");}return 0;}
