/* Actual two-pass synonym loader with physical heap/hunk and real source imports. */
#include Q3_CHAT_SOURCE
botlib_import_t botimport;
extern int numtokens;
static void *owners[256];
static int requests,failAt,liveOwners,opens,closes,fileReads,errors,warnings;
static const char *fileText;
static int sourceImports[2],sourcePositions[8],stagePosition;
static void Check(int ok,const char *message){if(!ok){fprintf(stderr,"Bot synonym regression failed: %s\n",message);exit(1);}}
void *GetMemory(unsigned long size){int i;Check(size>0&&size<=65536&&requests<256,"bounded parser allocation");requests++;if(opens>=1&&opens<=2&&sourceImports[opens-1]<4){sourcePositions[(opens-1)*4+sourceImports[opens-1]++]=requests;}if(requests==failAt)return NULL;for(i=0;i<256;i++)if(!owners[i]){owners[i]=malloc(size);Check(owners[i]!=NULL,"physical heap allocation");liveOwners++;return owners[i];}Check(0,"bounded physical heap owners");return NULL;}
void *GetClearedMemory(unsigned long size){void *p;if(opens==1&&closes==1&&!liveOwners){stagePosition=requests+1;sourceImports[0]=4;}p=GetMemory(size);if(p)memset(p,0,size);return p;}
void FreeMemory(void *p){int i;Check(p!=NULL,"release known physical heap owner");for(i=0;i<256;i++)if(owners[i]==p){free(p);owners[i]=NULL;liveOwners--;return;}Check(0,"release physical heap owner exactly once");}
#ifndef Com_Memcpy
void Com_Memcpy(void *out,const void *in,size_t size){memcpy(out,in,size);}
#endif
#ifndef Com_Memset
void Com_Memset(void *out,int value,size_t size){memset(out,value,size);}
#endif
void QDECL Com_Error(int level,const char *format,...){fprintf(stderr,"Fatal source state: level=%d requests=%d failAt=%d opens=%d owners=%d format=%s\n",level,requests,failAt,opens,liveOwners,format);Check(0,"unexpected engine fatal error");}
void QDECL Com_Printf(const char *format,...){(void)format;}
void QDECL Log_Write(char *format,...){(void)format;}
static void QDECL Print(int level,char *format,...){(void)format;if(level==PRT_ERROR||level==PRT_FATAL)errors++;else if(level==PRT_WARNING)warnings++;else Check(level==PRT_MESSAGE,"native print level");}
static int Open(const char *path,fileHandle_t *file,fsMode_t mode){Check(mode==FS_READ&&strlen(path)<MAX_QPATH,"fitting source path");opens++;*file=1;return (int)strlen(fileText);}
static int Read(void *out,int length,fileHandle_t file){Check(file==1&&length==(int)strlen(fileText),"exact source read");memcpy(out,fileText,length);fileReads++;return length;}
static void Close(fileHandle_t file){Check(file==1,"known source close");closes++;}
static void Reset(const char *text){Check(!liveOwners&&!numtokens,"previous physical owners released");fileText=text;requests=failAt=opens=closes=fileReads=errors=warnings=stagePosition=0;memset(sourceImports,0,sizeof(sourceImports));memset(sourcePositions,0,sizeof(sourcePositions));botimport.Print=Print;botimport.FS_FOpenFile=Open;botimport.FS_Read=Read;botimport.FS_FCloseFile=Close;}
#include <stdint.h>
static void *hunkBlock;
static unsigned long hunkSize;
static int hunkRequests,hunkFail,secondMissing,rootOpens;
static const char *firstText,*secondText;
static const char *nativeText="1 { [ (\"native1\",1.25),(\"native2\",2.5) ] 2 { [ (\"native3\",0),(\"native4\",4) ] } [ (\"native5\",3),(\"native6\",5) ] }";
void *GetClearedHunkMemory(unsigned long size){hunkRequests++;Check(size>0&&size<=65536&&!hunkBlock,"bounded single hunk publication");if(hunkFail)return NULL;hunkBlock=calloc(1,size);Check(hunkBlock!=NULL,"physical hunk allocation");hunkSize=size;return hunkBlock;}
static int SynOpen(const char *path,fileHandle_t *file,fsMode_t mode){const char *text;if(strstr(path,"broken.inc")){fileText="#unknown\n";return Open(path,file,mode);}if(secondMissing&&rootOpens){opens++;rootOpens++;*file=0;return -1;}text=rootOpens++?secondText:firstText;fileText=text;return Open(path,file,mode);}
static void SynBegin(const char *first,const char *second){Check(!hunkBlock,"previous hunk owner explicitly torn down");Reset(first);firstText=first;secondText=second?second:first;hunkRequests=hunkFail=secondMissing=rootOpens=0;hunkSize=0;botimport.FS_FOpenFile=SynOpen;}
static void SynHunkEnd(void){Check(!liveOwners&&!numtokens,"all source/staged heap owners physically released");free(hunkBlock);hunkBlock=NULL;hunkSize=0;}
static int InHunk(const void *pointer,unsigned long bytes){uintptr_t begin=(uintptr_t)hunkBlock,at=(uintptr_t)pointer;return at>=begin&&at-begin<=hunkSize&&bytes<=hunkSize-(at-begin);}
static void SynGolden(const char *first,const char *second){bot_synonymlist_t *list,*current;unsigned long contexts[]={1,3,1};float totals[]={3.75,4,8};const char *words[]={"native1","native2","native3","native4","native5","native6"};float weights[]={1.25,2.5,0,4,3,5};int i=0,j=0;SynBegin(first,second);list=BotLoadSynonyms("syn.c");Check(list&&hunkRequests==1&&!liveOwners&&!numtokens&&!errors&&opens==2&&closes==2,"complete native synonyms publish once after source/staging release");for(current=list;current;current=current->next){bot_synonym_t *entry;Check(i<3&&InHunk(current,sizeof(*current))&&current->context==contexts[i]&&current->totalweight==totals[i],"native context order and total weights");for(entry=current->firstsynonym;entry;entry=entry->next){Check(j<6&&InHunk(entry,sizeof(*entry))&&InHunk(entry->string,strlen(entry->string)+1)&&!strcmp(entry->string,words[j])&&entry->weight==weights[j],"native synonym text/order/weights and rebased physical owners");j++;}i++;}Check(i==3&&j==6,"all native lists/entries retained");SynHunkEnd();}
static void SynMalformed(const char *text,int second){bot_synonymlist_t *list;SynBegin(second?nativeText:text,second?text:NULL);list=BotLoadSynonyms("syn.c");Check(!list&&errors>0&&!liveOwners&&!numtokens&&!hunkRequests,"malformed first/second pass rejects without source/staging/hunk publication");SynHunkEnd();}
static void SynFailure(int index){bot_synonymlist_t *list;int target;SynBegin(nativeText,NULL);list=BotLoadSynonyms("syn.c");Check(list!=NULL,"native allocation trace prepares");target=index==8?stagePosition:sourcePositions[index];Check(target>0,"real source/staging import position identified");SynHunkEnd();SynBegin(nativeText,NULL);failAt=target;list=BotLoadSynonyms("syn.c");Check(!list&&requests==target&&!liveOwners&&!numtokens&&!hunkRequests,"each nullable source/staging import rolls back all earlier owners");failAt=0;opens=closes=fileReads=rootOpens=0;list=BotLoadSynonyms("syn.c");Check(list&&!liveOwners&&!numtokens&&hunkRequests==1,"nullable synonym construction retries");SynHunkEnd();}
static void SynHunkFailure(void){SynBegin(nativeText,NULL);hunkFail=1;Check(!BotLoadSynonyms("syn.c")&&errors==1&&hunkRequests==1&&!hunkBlock&&!liveOwners&&!numtokens,"nullable final hunk import releases staged owners");SynHunkEnd();}
static void SynChanged(int shrink){SynBegin(shrink?nativeText:"1 { [ (\"native1\",1.25),(\"native2\",2.5) ] }",shrink?"1 { [ (\"native1\",1.25),(\"native2\",2.5) ] }":nativeText);Check(!BotLoadSynonyms("syn.c")&&errors>0&&!liveOwners&&!numtokens&&!hunkRequests,"changed second-pass capacity rejects before publication");SynHunkEnd();}
static void SynSecondMissing(void){SynBegin(nativeText,NULL);secondMissing=1;Check(!BotLoadSynonyms("syn.c")&&errors==1&&!liveOwners&&!numtokens&&!hunkRequests&&opens==2&&closes==1,"failed second source releases heap staging");SynHunkEnd();}
int main(int argc,char **argv){if(argc>1){int proof=atoi(argv[1]);if(proof==0)SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ]",0);else if(proof==1)SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ] }\n#unknown\n",0);else if(proof==2)SynChanged(0);else if(proof==3)SynChanged(1);else if(proof==4)SynSecondMissing();else if(proof==5)SynHunkFailure();else if(proof==6)SynMalformed("1 { [ (\"native1\",99999999999999999999999999999999999999999999999999999999999999999999999999999.0),(\"native2\",2) ] }",0);else if(proof==7)SynMalformed("1 { [ (\"native1\",340282346638528859811704183484516925440.0),(\"native2\",340282346638528859811704183484516925440.0) ] }",0);else if(proof==8){bot_synonymlist_t *list;SynBegin("1 { [ (\"first\",1),(\"last\",2) ] }",NULL);list=BotLoadSynonyms("syn.c");Check(list&&!errors&&!liveOwners&&!numtokens,"odd-sized strings retain aligned complete owner publication");SynHunkEnd();}else if(proof==9)SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ] } \"unterminated",1);else if(proof>=11&&proof<=14)SynFailure(proof-7);else SynGolden(nativeText,NULL);return 0;}
SynGolden(nativeText,NULL);SynGolden(nativeText,nativeText);SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ]",0);SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ] }\n#unknown\n",0);SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ] } \"unterminated",0);SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ] } \"unterminated",1);SynMalformed("1 { [ (\"native1\",1) ] }",1);SynMalformed("1 { [ (\"\",1),(\"native2\",2) ] }",1);SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ] } }",1);SynMalformed("1 { [ (\"native1\",99999999999999999999999999999999999999999999999999999999999999999999999999999.0),(\"native2\",2) ] }",0);SynMalformed("1 { [ (\"native1\",340282346638528859811704183484516925440.0),(\"native2\",340282346638528859811704183484516925440.0) ] }",0);SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ] }\n#include \"broken.inc\"\n",0);SynMalformed("1 { [ (\"native1\",1),(\"native2\",2) ] }\n#include \"broken.inc\"\n",1);SynChanged(0);SynChanged(1);SynSecondMissing();SynHunkFailure();{int i;for(i=0;i<9;i++)SynFailure(i);}{bot_synonymlist_t *list;SynBegin("1 { [ (\"first\",1),(\"last\",2) ] }",NULL);list=BotLoadSynonyms("syn.c");Check(list&&!errors&&!liveOwners&&!numtokens,"odd-sized entries are aligned");SynHunkEnd();}SynBegin("",NULL);Check(!BotLoadSynonyms("syn.c")&&!errors&&!liveOwners&&!numtokens&&!hunkRequests,"empty native source retains no synonyms");SynHunkEnd();SynBegin(nativeText,NULL);Check(!BotLoadSynonyms(NULL)&&!BotLoadSynonyms("")&&errors==2&&!requests&&!opens&&!hunkRequests,"missing filenames reject before imports");SynHunkEnd();puts("Real synonym source status, aligned two-pass staging, native values and heap/hunk rollback passed (issue #48)");return 0;}
