/* Actual engine map API checks the internal status; retail export stays void. */
#define Q3_ITEM_NATIVE_INTERFACE
#define Q3_LEVEL_POOL_ENTRY PoolFixtureMain
#include "bot_level_pool_regression.c"
extern int Export_BotLibLoadMap(const char *mapname);
extern int Export_BotLibVarGet(char *name,char *value,int size);
static int mapLoads,brushCalls,mapError;
int AAS_LoadMap(const char *name){Check(!strcmp(name,"native"),"native map API name");mapLoads++;return mapError;}
void BotSetBrushModelTypes(void){brushCalls++;}
static void ApiBegin(int occupied){PriorPool(occupied);memset(&botlibglobals,0,sizeof(botlibglobals));botlibglobals.botlibsetup=1;botlibglobals.mapready=occupied;mapLoads=brushCalls=mapError=0;botDeveloper=0;}
static void ApiFailure(int occupied,int fault){levelitem_t *prior,*active,*freehead,nodes[2];int baseline;ApiBegin(occupied);prior=levelitemheap;active=levelitems;freehead=freelevelitems;if(prior)memcpy(nodes,prior,sizeof(nodes));baseline=heapLive;failAt=fault;Check(Export_BotLibLoadMap("native")==BLERR_LIBRARYNOTSETUP&&!botlibglobals.mapready&&mapLoads==1&&!brushCalls&&!infoCalls&&errors==1&&messages==1&&requests==fault&&heapLive==baseline+(fault==3?2:0)&&levelitemheap==prior&&levelitems==active&&freelevelitems==freehead&&numlevelitems==occupied,"actual map API propagates nullable pool setup failure before brush/success handling and retains native prior state");if(prior)Check(!memcmp(nodes,prior,sizeof(nodes)),"map API failure keeps complete prior pool payload");Attempt(nativeText);mapLoads=brushCalls=0;Check(Export_BotLibLoadMap("native")==BLERR_NOERROR&&botlibglobals.mapready&&mapLoads==1&&brushCalls==1&&infoCalls==1&&messages==2&&!errors&&heapLive==3&&levelitemheap&&freelevelitems==levelitemheap&&!levelitems&&!numlevelitems,"actual map API retries complete native pool initialization and brush order");PoolEnd();}
static void ApiInvalid(void){libvar_t *variable;levelitem_t *prior;int imports;ApiBegin(1);prior=levelitemheap;variable=LibVar("max_levelitems","256");Check(variable!=NULL,"actual invalid map count cache prepares");variable->value=Opaque(0x7fc00000U);imports=requests;Check(Export_BotLibLoadMap("native")==BLERR_LIBRARYNOTSETUP&&requests==imports&&!botlibglobals.mapready&&mapLoads==1&&!brushCalls&&!infoCalls&&errors==1&&levelitemheap==prior&&numlevelitems==1,"actual map API rejects NaN pool count without false success or stale list replacement");PoolEnd();}
static void ApiGolden(void){ApiBegin(0);Check(Export_BotLibLoadMap("native")==BLERR_NOERROR&&botlibglobals.mapready&&mapLoads==1&&brushCalls==1&&infoCalls==1&&messages==2&&!errors&&heapLive==3&&levelitemheap&&freelevelitems==levelitemheap&&!levelitems&&!numlevelitems,"native successful map API value and call order");PoolEnd();}
static void ApiEarly(void){levelitem_t *prior;ApiBegin(1);prior=levelitemheap;botlibglobals.botlibsetup=0;Check(Export_BotLibLoadMap("native")==BLERR_LIBRARYNOTSETUP&&!mapLoads&&!brushCalls&&!infoCalls&&!requests&&errors==1&&levelitemheap==prior,"native uninitialized library map gate remains");botlibglobals.botlibsetup=1;Attempt(nativeText);mapError=BLERR_CANNOTOPENAASFILE;Check(Export_BotLibLoadMap("native")==BLERR_CANNOTOPENAASFILE&&!botlibglobals.mapready&&mapLoads==1&&!brushCalls&&!infoCalls&&!requests&&!errors&&levelitemheap==prior,"native AAS map failure propagates before goal initialization");PoolEnd();}
static void ApiReady(void){char value[3]={'x','x','Z'};int imports;ApiBegin(0);imports=requests;Check(Export_BotLibVarGet("botlib_mapready",value,2)==BLERR_NOERROR&&value[0]=='0'&&!value[1]&&value[2]=='Z'&&requests==imports,"engine status query is bounded and allocates no cache");LibVarSet("botlib_mapready","1");Check(!strcmp(LibVarGetString("botlib_mapready"),"1"),"prepare attempted stale user variable");imports=requests;Check(Export_BotLibVarGet("botlib_mapready",value,2)==BLERR_NOERROR&&value[0]=='0'&&!value[1]&&requests==imports,"user variable cannot revive engine readiness");Check(Export_BotLibLoadMap("native")==BLERR_NOERROR&&botlibglobals.mapready,"complete map publishes retained engine readiness");imports=requests;Check(Export_BotLibVarGet("botlib_mapready",value,2)==BLERR_NOERROR&&value[0]=='1'&&!value[1]&&requests==imports,"complete status survives game module reset without allocations");botlibglobals.botlibsetup=0;Check(Export_BotLibVarGet("botlib_mapready",value,2)==BLERR_NOERROR&&value[0]=='0'&&!value[1],"uninitialized library cannot expose stale ready status");PoolEnd();}
int main(int argc,char **argv){int occupied,fault,i;if(argc>1){i=atoi(argv[1]);if(i<6)ApiFailure(i/3,i%3+1);else if(i==6)ApiInvalid();else{ApiGolden();ApiEarly();}return 0;}for(occupied=0;occupied<2;occupied++)for(fault=1;fault<=3;fault++)ApiFailure(occupied,fault);ApiInvalid();ApiGolden();ApiEarly();ApiReady();puts("Actual engine map API propagates pool errors and preserves retail void ABI/native success and early gates (issues #47/#48)");return 0;}
