/* Actual unread/indent factories with prior source owners and nullable callbacks. */
#define Q3_EVAL_ENTRY EvalFixtureMain
#include "bot_eval_regression.c"
extern int PC_UnreadSourceToken(source_t *,token_t *);
extern int PC_ReadLine(source_t *,token_t *);
#ifndef Q3_FACTORY_ORIGINAL
extern int PC_PushIndent(source_t *,int,int);
#endif
extern void PC_PopIndent(source_t *,int *,int *);
extern int PC_Directive_if(source_t *);
extern int PC_Directive_ifdef(source_t *);
extern int PC_Directive_ifndef(source_t *);
extern int PC_Directive_else(source_t *);
extern int PC_Directive_elif(source_t *);
static void FactoryUnread(int occupied){source_t *source=EvalStart("native");token_t token;token_t *prior=NULL;unsigned char saved[sizeof(token_t)],caller[sizeof(token_t)];int base;Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"native"),"actual native unread input");memcpy(caller,&token,sizeof(token));if(occupied){Check(PC_UnreadSourceToken(source,&token),"existing real queued owner prepares");prior=source->tokens;memcpy(saved,prior,sizeof(*prior));}base=liveOwners;failAt=requests+1;Check(!PC_UnreadSourceToken(source,&token)&&fatals==1&&errors==1&&PC_SourceHasError(source)&&source->tokens==prior&&liveOwners==base&&numtokens==occupied&&!memcmp(caller,&token,sizeof(token)),"nullable unread keeps complete existing queue/caller/source owners");if(occupied)Check(!memcmp(saved,prior,sizeof(*prior)),"existing queued token bytes remain complete");failAt=0;Check(PC_UnreadSourceToken(source,&token),"failed unread retries through historical source status");Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"native"),"retried native token order");if(occupied)Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"native"),"prior queued token still readable");EvalEnd(source);}
static void FactoryLine(void){source_t *source=EvalStart("first\nnext");token_t token;Check(PC_ReadLine(source,&token)&&!strcmp(token.string,"first"),"native first line");failAt=requests+1;Check(!PC_ReadLine(source,&token)&&errors==1&&fatals==1&&PC_SourceHasError(source)&&!source->tokens&&!numtokens&&liveOwners==4,"failed line lookahead unread records source failure without partial queue");EvalEnd(source);}
#ifndef Q3_FACTORY_ORIGINAL
static void FactoryIndent(void){source_t *source=EvalStart("native");indent_t *prior;unsigned char saved[sizeof(indent_t)];int skip,type,outskip;Check(PC_PushIndent(source,INDENT_IF,1),"native prior conditional owner prepares");prior=source->indentstack;memcpy(saved,prior,sizeof(*prior));skip=source->skip;failAt=requests+1;Check(!PC_PushIndent(source,INDENT_IFDEF,0)&&errors==1&&!fatals&&PC_SourceHasError(source)&&source->indentstack==prior&&source->skip==skip&&!memcmp(saved,prior,sizeof(*prior))&&liveOwners==5&&!numtokens,"failed indent allocation preserves prior complete stack/skip owners");failAt=0;Check(PC_PushIndent(source,INDENT_IFNDEF,9)&&source->skip==skip+1,"failed indent retries with native boolean skip");PC_PopIndent(source,&type,&outskip);Check(type==INDENT_IFNDEF&&outskip==1&&source->indentstack==prior&&source->skip==skip,"native nested pop restores original stack/skip");EvalEnd(source);}
#endif
static void FactoryDirective(int entry){int (*calls[3])(source_t *)={PC_Directive_if,PC_Directive_ifdef,PC_Directive_ifndef};const char *body=entry?"unknown":"1\nnext";source_t *source=EvalStart(body);int target;Check(calls[entry](source),"healthy native conditional import trace");target=requests;EvalEnd(source);source=EvalStart(body);failAt=target;Check(!calls[entry](source)&&errors==1&&!fatals&&PC_SourceHasError(source)&&!source->indentstack&&!source->skip,"conditional callers propagate nullable indent failure");if(entry)Check(liveOwners==4&&!numtokens&&!source->tokens,"name conditional failure keeps complete source only");else Check(liveOwners==5&&numtokens==1&&source->tokens&&!source->tokens->next&&!strcmp(source->tokens->string,"next"),"expression conditional failure keeps native next-line token owner");EvalEnd(source);}
static void FactoryReplacement(int branch,int skip,int fault){source_t *source=EvalStart("unknown 1\nbody\n#endif\ntail");indent_t *prior;unsigned char saved[sizeof(indent_t)];token_t token;int base,imports;Check((skip?PC_Directive_ifdef:PC_Directive_ifndef)(source),"actual native prior branch prepares");prior=source->indentstack;memcpy(saved,prior,sizeof(*prior));base=liveOwners;imports=requests;failAt=imports+fault;if(branch&&fault<=2){Check(!PC_Directive_elif(source)&&errors==1&&fatals==1&&PC_SourceHasError(source)&&source->indentstack==prior&&source->skip==skip&&!memcmp(saved,prior,sizeof(*prior))&&liveOwners==base&&!numtokens,"failed elif operand/lookahead retains complete prior frame/skip owners");failAt=0;if(!skip&&fault==1)Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"body"),"failed expression recovery retains active body");Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"tail")&&!source->indentstack&&!source->skip,"failed expression recovery closes original conditional without misplaced endif");}else{Check((branch?PC_Directive_elif:PC_Directive_else)(source)&&source->indentstack==prior&&prior->type==(branch?INDENT_ELIF:INDENT_ELSE)&&source->skip==(branch?0:!skip)&&liveOwners==base+(branch?1:0)&&requests==imports+(branch?2:0)&&!errors&&!fatals,"else/elif reuse complete native frame without replacement allocation");failAt=0;}EvalEnd(source);}
static void FactoryElifEnd(const char *text){source_t *source=EvalStart(text);Check(PC_Directive_ifdef(source)&&source->indentstack&&source->skip==1,"native skipped prior EOF conditional");Check(!PC_Directive_elif(source)&&errors>0&&!source->indentstack&&!source->skip&&liveOwners==4&&!numtokens,"elif EOF safely unwinds without a stale frame or invalid skip count");EvalEnd(source);}
static void FactoryElifInclude(void){source_t *source=EvalStart("unknown\nbody\n#endif\ntail");script_t *parent=source->scriptstack,*child;indent_t *prior;unsigned char saved[sizeof(indent_t)];token_t token;Check(PC_Directive_ifndef(source),"native parent include conditional");prior=source->indentstack;memcpy(saved,prior,sizeof(*prior));child=LoadScriptMemory("unknown 1",9,"native-child");Check(child!=NULL,"actual included script owners prepare");child->next=parent;source->scriptstack=child;Check(PC_Directive_ifdef(source),"native child condition prepares");Check(!PC_Directive_elif(source)&&errors==1&&warnings==1&&!fatals&&source->scriptstack==parent&&source->indentstack==prior&&!memcmp(saved,prior,sizeof(*prior))&&!source->skip&&liveOwners==6&&numtokens==1,"child EOF rejects elif without mutating the enclosing script frame");Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"body")&&PC_ReadToken(source,&token)&&!strcmp(token.string,"tail")&&!source->indentstack&&!source->skip,"enclosing native script recovers after child EOF");EvalEnd(source);}
static void FactoryGolden(void){source_t *source;token_t token;const char *names[]={"first","nested","other","tail"};int i;source=EvalStart("#if 1\nfirst\n#ifdef unknown\nignored\n#else\nnested\n#endif\n#endif\n#ifndef unknown\nother\n#endif\ntail");for(i=0;i<4;i++)Check(PC_ReadToken(source,&token)&&!strcmp(token.string,names[i]),"native conditional/name/token order remains");Check(!PC_ReadToken(source,&token)&&!errors&&!fatals&&!numtokens&&!source->indentstack&&!source->skip&&liveOwners==4,"native conditional EOF releases all stack owners");EvalEnd(source);source=EvalStart("#if 0\nignored\n#elif 1\nfirst\n#else\nignored\n#endif\ntail");Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"first")&&PC_ReadToken(source,&token)&&!strcmp(token.string,"tail")&&!PC_ReadToken(source,&token)&&!errors&&!fatals&&!source->indentstack&&!source->skip&&liveOwners==4,"native elif selection and EOF ownership remain");EvalEnd(source);source=EvalStart("alpha beta");Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"alpha")&&PC_UnreadSourceToken(source,&token)&&PC_ReadToken(source,&token)&&!strcmp(token.string,"alpha")&&PC_ReadToken(source,&token)&&!strcmp(token.string,"beta")&&!PC_ReadToken(source,&token)&&!errors&&!numtokens,"native unread roundtrip/order remains");EvalEnd(source);}
int main(int argc,char **argv){if(argc>1){int proof=atoi(argv[1]);if(proof<2)FactoryUnread(proof);else if(proof==2)FactoryLine();else if(proof>=3&&proof<=5)FactoryDirective(proof-3);else if(proof==6)FactoryReplacement(0,1,1);else if(proof==7)FactoryReplacement(1,1,3);else if(proof==8)FactoryReplacement(1,1,1);else if(proof==9)FactoryReplacement(1,1,2);else if(proof==10)FactoryElifEnd("unknown 1");else if(proof==11)FactoryElifInclude();else FactoryGolden();return 0;}FactoryUnread(0);FactoryUnread(1);FactoryLine();
#ifndef Q3_FACTORY_ORIGINAL
FactoryIndent();
#endif
FactoryDirective(0);FactoryDirective(1);FactoryDirective(2);{int skip,fault;for(skip=0;skip<2;skip++){FactoryReplacement(0,skip,1);FactoryReplacement(1,skip,3);for(fault=1;fault<=2;fault++)FactoryReplacement(1,skip,fault);}}FactoryElifEnd("unknown 1");FactoryElifEnd("unknown");FactoryElifEnd("unknown 1 / 0");FactoryElifInclude();FactoryGolden();puts("Real unread/indent nullable factories, prior owners, failure propagation and native token order passed (issue #48)");return 0;}
