/* Actual metadata staging and public pool/map publication using native BSP epairs. */
#define Q3_ITEM_NATIVE_INTERFACE
#define Q3_POOL_BSP_HOOKS
#define Q3_LEVEL_POOL_ENTRY PoolFixtureMain
#include "bot_level_pool_regression.c"
static int bspIterations;
int AAS_NextBSPEntity(int entity){Check(entity>=0&&entity<=5,"bounded native fixture entity");bspIterations++;return entity==5?0:entity+1;}
int AAS_ValueForBSPEpairKey(int entity,char *key,char *out,int size){const char *value=NULL;Check(entity>=1&&entity<=5,"native fixture dictionary entity");if(!strcmp(key,"classname"))value=entity==1||entity==5?"target_location":entity==2||entity==4?"info_camp":"worldspawn";else if(!strcmp(key,"message"))value=entity==1?"Alpha":entity==5?"Omega":entity==2?"Camp":"Solid";else Check(0,"only native metadata dictionary keys");Check(value&&strlen(value)<(size_t)size,"complete fitting native metadata value");strcpy(out,value);return 1;}
int AAS_VectorForBSPEpairKey(int entity,char *key,vec3_t out){Check(!strcmp(key,"origin")&&entity>=1&&entity<=5,"native metadata origin key");out[0]=(float)entity;out[1]=(float)entity+1;out[2]=(float)entity+2;return 1;}
int AAS_FloatForBSPEpairKey(int entity,char *key,float *out){Check(entity==2||entity==4,"native camp scalar entity");if(!strcmp(key,"range"))*out=100;else if(!strcmp(key,"weight"))*out=200;else if(!strcmp(key,"wait"))*out=10;else if(!strcmp(key,"random"))*out=5;else Check(0,"only native camp scalar keys");return 1;}
int AAS_IntForBSPEpairKey(int entity,char *key,int *out){(void)entity;(void)key;(void)out;Check(0,"unreachable no-item native BSP integer");return 0;}
int AAS_PointAreaNum(vec3_t point){return point[0]==4?0:(int)point[0]+10;}
static void MapPrior(int occupied){PriorPool(occupied);Check(!maplocations&&!campspots,"prior native metadata released");if(occupied){maplocations=GetClearedMemory(sizeof(maplocation_t));campspots=GetClearedMemory(sizeof(campspot_t));Check(maplocations&&campspots,"complete prior native info heap owners");strcpy(maplocations->name,"Prior location");strcpy(campspots->name,"Prior camp");maplocations->areanum=71;campspots->weight=777;}Attempt(nativeText);bspIterations=0;}
static void MapEnd(void){BotFreeInfoEntities();PoolEnd();}
static void InfoValues(void){Check(maplocations&&maplocations->next&&!maplocations->next->next&&!strcmp(maplocations->name,"Omega")&&!strcmp(maplocations->next->name,"Alpha")&&maplocations->areanum==15&&maplocations->next->areanum==11&&maplocations->origin[0]==5&&maplocations->next->origin[0]==1,"native location reverse-order names/origins/areas");Check(campspots&&!campspots->next&&!strcmp(campspots->name,"Camp")&&campspots->origin[0]==2&&campspots->areanum==12&&campspots->range==100&&campspots->weight==200&&campspots->wait==10&&campspots->random==5,"native camp values and solid camp omission");}
static void InfoGolden(int public){MapPrior(0);if(public==2)Check(BotInitLevelItemsChecked()==BLERR_NOERROR,"checked native metadata success");else if(public)BotInitLevelItems();else Check(BotInitInfoEntities(),"native private info success");InfoValues();Check(heapLive==(public?6:3)&&!hunkLive&&!errors&&!warnings&&messages==1&&bspIterations==6,"native complete info physical owners and solid-camp diagnostic");if(public)Check(levelitemheap&&freelevelitems==levelitemheap&&!levelitems&&!numlevelitems,"complete public metadata also publishes cleared native pool");MapEnd();}

static void InfoFailure(int occupied,int fault,int public){maplocation_t *priorlocation,location; campspot_t *priorcamp,camp;levelitem_t *priorpool,*priorfree,*prioractive,nodes[2];int baseline;MapPrior(occupied);priorlocation=maplocations;priorcamp=campspots;priorpool=levelitemheap;priorfree=freelevelitems;prioractive=levelitems;if(occupied){location=*priorlocation;camp=*priorcamp;memcpy(nodes,priorpool,sizeof(nodes));}baseline=heapLive;failAt=fault;if(public==2)Check(BotInitLevelItemsChecked()==BLERR_LIBRARYNOTSETUP,"checked native metadata rejects failed staging");else if(public)BotInitLevelItems();else Check(!BotInitInfoEntities(),"private staged metadata reports failed allocation");Check(requests==fault&&errors==1&&heapLive==baseline+(public&&fault>=3?2:0)&&!hunkLive&&maplocations==priorlocation&&campspots==priorcamp&&levelitemheap==priorpool&&freelevelitems==priorfree&&levelitems==prioractive&&numlevelitems==occupied,"all nullable metadata stages preserve complete prior roots/list/count and release private owners");if(occupied)Check(!memcmp(&location,priorlocation,sizeof(location))&&!memcmp(&camp,priorcamp,sizeof(camp))&&!memcmp(nodes,priorpool,sizeof(nodes)),"all nullable stages retain every prior metadata and pool payload byte");if(public&&fault<=3)Check(!bspIterations,"failed pool stage does not query or replace map metadata");Attempt(nativeText);bspIterations=0;if(public==2)Check(BotInitLevelItemsChecked()==BLERR_NOERROR,"checked native metadata success");else if(public)BotInitLevelItems();else Check(BotInitInfoEntities(),"failed private metadata retries");InfoValues();Check(!errors&&messages==1&&heapLive==(public?6:3+occupied)&&bspIterations==6,"nullable metadata retries with native complete fields and physical owner counts");if(public)Check(levelitemheap&&freelevelitems==levelitemheap&&!levelitems&&!numlevelitems,"complete public retry replaces all roots together");else Check(levelitemheap==priorpool&&levelitems==prioractive&&numlevelitems==occupied,"private info retry leaves independent prior pool/list intact");MapEnd();}
extern int Export_BotLibLoadMap(const char *name);
static int mapLoads,brushCalls;
int AAS_LoadMap(const char *name){Check(!strcmp(name,"native"),"native metadata map API name");mapLoads++;return BLERR_NOERROR;}
void BotSetBrushModelTypes(void){brushCalls++;}
static void MapApiFailure(int occupied,int fault){levelitem_t *pool;maplocation_t *location;campspot_t *camp;int baseline;MapPrior(occupied);pool=levelitemheap;location=maplocations;camp=campspots;baseline=heapLive;botlibglobals.botlibsetup=1;mapLoads=brushCalls=0;failAt=fault;Check(Export_BotLibLoadMap("native")==BLERR_LIBRARYNOTSETUP&&mapLoads==1&&!brushCalls&&errors==1&&requests==fault&&heapLive==baseline+(fault>=3?2:0)&&levelitemheap==pool&&maplocations==location&&campspots==camp&&numlevelitems==occupied,"actual map API propagates every metadata staging failure without replacing prior roots or running brush success");Attempt(nativeText);bspIterations=mapLoads=brushCalls=0;Check(Export_BotLibLoadMap("native")==BLERR_NOERROR&&mapLoads==1&&brushCalls==1&&!errors&&messages==3&&heapLive==6&&bspIterations==6,"actual metadata map API retries complete native roots and success order");InfoValues();MapEnd();}
int main(int argc,char **argv){int i,occupied,fault,public;if(argc>1){i=atoi(argv[1]);if(i<8)InfoFailure(i/4,i%4+1,0);else if(i<16)InfoFailure((i-8)/4,(i-8)%4+4,1);else if(i<22)InfoFailure((i-16)/3,(i-16)%3+1,1);else InfoGolden(i-22);return 0;}for(public=0;public<3;public++)for(occupied=0;occupied<2;occupied++)for(fault=1;fault<=(public?7:4);fault++)InfoFailure(occupied,fault,public);InfoGolden(0);InfoGolden(1);InfoGolden(2);for(occupied=0;occupied<2;occupied++)for(fault=1;fault<=7;fault++)MapApiFailure(occupied,fault);puts("Actual map metadata/private/public roots, 36 nullable rollback stages, native epair values and physical heap ownership passed (issues #47/#48)");return 0;}
