/* Actual native weight configuration parsing, cache publication and owner rollback. */
#include Q3_WEIGHT_SOURCE
botlib_import_t botimport;
extern int numtokens;
static void *owners[2048];
static unsigned long costs[2048],requestCosts[2048];
static int liveOwners,requests,failAt,opens,closes,reads,errors,warnings,messages;
static const char *rootText,*innerText,*leafText,*readingText;
static weightconfig_t *preserved;
static void Check(int condition,const char *message){if(!condition){fprintf(stderr,"Bot weight regression failed: %s\n",message);exit(1);}}
static void CacheCheck(void){int i;for(i=0;i<MAX_WEIGHT_FILES;i++)Check(weightFileList[i]==(i==0?preserved:NULL),"failed/private parsing preserves exact cache slots");}
void *GetMemory(unsigned long size){int i;CacheCheck();Check(size&&size<=65536&&requests<2048,"bounded native weight/parser heap request");requestCosts[requests++]=size;if(requests==failAt)return NULL;for(i=0;i<2048;i++)if(!owners[i]){owners[i]=malloc(size);Check(owners[i]!=NULL,"fixture heap allocation");costs[i]=size;liveOwners++;return owners[i];}Check(0,"bounded physical owners");return NULL;}
void *GetClearedMemory(unsigned long size){void *p=GetMemory(size);if(p)memset(p,0,size);return p;}
void FreeMemory(void *p){int i;Check(p!=NULL,"release only owned nonnull allocations");for(i=0;i<2048;i++)if(owners[i]==p){free(p);owners[i]=NULL;costs[i]=0;liveOwners--;return;}Check(0,"physical allocation releases exactly once");}
#ifndef Com_Memcpy
void Com_Memcpy(void *out,const void *in,size_t length){memcpy(out,in,length);}
#endif
#ifndef Com_Memset
void Com_Memset(void *out,int value,size_t length){memset(out,value,length);}
#endif
void QDECL Com_Error(int level,const char *format,...){(void)level;(void)format;Check(0,"unexpected native fatal error");}
void QDECL Com_Printf(const char *format,...){(void)format;Check(0,"unexpected core formatting warning");}
void QDECL Log_Write(char *format,...){(void)format;}
static void QDECL Print(int level,char *format,...){(void)format;if(level==PRT_ERROR||level==PRT_FATAL)errors++;else if(level==PRT_WARNING)warnings++;else{Check(level==PRT_MESSAGE,"native print severity");messages++;}}
static int Open(const char *path,fileHandle_t *file,fsMode_t mode){Check(mode==FS_READ&&strlen(path)<MAX_QPATH,"complete bounded native VFS lookup");{const char *base=strrchr(path,'/');base=base?base+1:path;readingText=!strcmp(base,"one.c")?innerText:!strcmp(base,"two.c")?leafText:rootText;}Check(readingText!=NULL,"known native source bytes");opens++;*file=opens;return (int)strlen(readingText);}
static int Read(void *out,int length,fileHandle_t file){Check(file==opens&&length==(int)strlen(readingText),"complete actual source file read");memcpy(out,readingText,length);reads++;return length;}
static void Close(fileHandle_t file){Check(file==opens,"known current native file owner");closes++;}
static void Attempt(const char *text){rootText=text;innerText=leafText="";requests=failAt=opens=closes=reads=errors=warnings=messages=0;memset(requestCosts,0,sizeof(requestCosts));botimport.Print=Print;botimport.FS_FOpenFile=Open;botimport.FS_Read=Read;botimport.FS_FCloseFile=Close;CacheCheck();}
static void Finish(void){preserved=NULL;BotShutdownWeights();LibVarDeAllocAll();Check(!liveOwners&&!numtokens,"all weight/source/libvar owners physically release");CacheCheck();}
static const char *nativeText="weight \"plain\" return 42;\nweight \"tree\" { switch (1) { case 5: return 2.5; case 10: { switch (2) { default: return balance(7,3,9); } } default: return 11; } }\nweight \"implicit\" switch (3) { case 2: return 6; }";
static void Values(weightconfig_t *config){int inventory[8]={0};fuzzyseperator_t *fs;Check(config&&config->numweights==3&&!strcmp(config->filename,"bots/native.w"),"all native weight headers/names publish complete");Check(FindFuzzyWeight(config,"plain")==0&&FindFuzzyWeight(config,"tree")==1&&FindFuzzyWeight(config,"implicit")==2&&FindFuzzyWeight(config,"missing")==-1,"native weight-name lookup");fs=config->weights[1].firstseperator;Check(fs&&fs->index==1&&fs->value==5&&fs->weight==2.5f&&fs->next&&fs->next->value==10&&fs->next->child&&fs->next->child->type==WT_BALANCE&&fs->next->child->weight==7&&fs->next->child->minweight==3&&fs->next->child->maxweight==9&&fs->next->next&&fs->next->next->value==MAX_INVENTORYVALUE&&fs->next->next->weight==11,"native nested case/default/balance fields");Check(FuzzyWeight(inventory,config,0)==42&&FuzzyWeight(inventory,config,1)==2.5f&&FuzzyWeight(inventory,config,2)==6,"actual native ordinary weight evaluation");inventory[1]=MAX_INVENTORYVALUE;inventory[3]=MAX_INVENTORYVALUE;Check(FuzzyWeight(inventory,config,1)==11&&FuzzyWeight(inventory,config,2)==0,"native explicit/implicit default evaluation");}
static weightconfig_t *Golden(int reload){weightconfig_t *config;if(reload)LibVarSet("bot_reloadcharacters","1");Attempt(nativeText);config=ReadWeightConfig("bots/native.w");Values(config);Check(opens==1&&closes==1&&reads==1&&!errors&&warnings==1&&messages==1&&!numtokens,"native parser file closure/warnings before publication");Check(reload?!weightFileList[0]:weightFileList[0]==config,"native cached/reload publication semantics");return config;}
static void Valid(int reload){weightconfig_t *config=Golden(reload);int imports=requests;if(!reload){preserved=config;Check(ReadWeightConfig("bots/native.w")==config&&requests==imports&&opens==1,"native cache hit performs no source or heap imports");FreeWeightConfig(config);Check(weightFileList[0]==config,"public cached release retains native cache ownership");}else FreeWeightConfig(config);Finish();}
static void Failed(const char *text,int reload,int mode,int retain){weightconfig_t *config,*before=NULL;weightconfig_t snapshot;int baseline;if(retain){before=Golden(0);preserved=before;snapshot=*before;}else if(reload)LibVarSet("bot_reloadcharacters","1");baseline=liveOwners;Attempt(text);if(mode){innerText=mode==2?"#include \"two.c\"":"\"\\q\"";leafText="184467440737095516160";}config=ReadWeightConfig(retain?"bots/failed.w":"bots/native.w");Check(!config,"source/syntax failure rejects unpublished weight configuration");if(liveOwners!=baseline||numtokens||opens!=mode+1||closes!=opens||reads!=opens||errors<=0||messages)fprintf(stderr,"Failure state: reload=%d mode=%d retain=%d owners=%d baseline=%d tokens=%d opens=%d closes=%d reads=%d errors=%d messages=%d\n",reload,mode,retain,liveOwners,baseline,numtokens,opens,closes,reads,errors,messages);Check(liveOwners==baseline&&!numtokens&&opens==mode+1&&closes==opens&&reads==opens&&errors>0&&!messages,"failed parser releases all private file/source/name/tree owners");CacheCheck();if(before){Check(!memcmp(before,&snapshot,sizeof(snapshot)),"failed distinct load preserves complete cached header");Values(before);}Attempt(nativeText);config=ReadWeightConfig(retain?"bots/retry.w":"bots/native.w");Check(config&&config->numweights==3,"failed weight configuration retries");if(reload)FreeWeightConfig(config);Finish();}
static void NullStage(int reload,int position){weightconfig_t *config=Golden(reload);int targets[32],count=0,i,baseline;if(!reload)weightFileList[0]=NULL;for(i=0;i<requests;i++)if(requestCosts[i]==sizeof(weightconfig_t)||requestCosts[i]==sizeof(fuzzyseperator_t)||requestCosts[i]==6UL||requestCosts[i]==5UL||requestCosts[i]==9UL)targets[count++]=i+1;Check(count==11,"all configuration/name/ordinary/nested/default allocation stages identified");FreeWeightConfig2(config);baseline=liveOwners;Attempt(nativeText);failAt=targets[position];Check(!ReadWeightConfig("bots/native.w"),"nullable native weight stage rejects");Check(requests==failAt&&liveOwners==baseline&&!numtokens&&opens==1&&closes==1&&errors==1&&!messages,"each nullable weight stage rolls back its physical private owners");CacheCheck();Attempt(nativeText);config=ReadWeightConfig("bots/native.w");Values(config);if(reload)FreeWeightConfig(config);Finish();}
static void Capacity(void){char text[8192];int i,offset=0;weightconfig_t *config;for(i=0;i<=MAX_WEIGHTS;i++)offset+=snprintf(text+offset,sizeof(text)-(size_t)offset,"weight \"w%d\" return %d;\n",i,i);Attempt(text);config=ReadWeightConfig("bots/capacity.w");Check(config&&config->numweights==MAX_WEIGHTS&&FindFuzzyWeight(config,"w0")==0&&FindFuzzyWeight(config,"w127")==127&&FindFuzzyWeight(config,"w128")==-1&&config->weights[127].firstseperator->weight==127&&warnings==1&&!errors&&messages==1&&liveOwners==1+2*MAX_WEIGHTS,"native capacity retains 128 complete weights with one truncation warning");Finish();}
int main(int argc,char **argv){int i,reload;if(argc>1){int proof=atoi(argv[1]);if(proof==0)Failed("weight \"plain\" return 42;\n#unknown",0,0,0);else if(proof==1)Failed("weight \"plain\" return 42;\n#include \"one.c\"",0,1,0);else if(proof==2)Failed("weight \"first\" return 42; weight \"unfinished\"",0,0,0);else if(proof==3)Failed("weight \"tree\" switch (1) { case 5: invalid }",1,0,0);else if(proof<15)NullStage(0,proof-4);else if(proof==15)Failed("weight \"plain\" return #unknown\n42;",0,0,0);else {Valid(0);Valid(1);Capacity();}}
else{Valid(0);Valid(1);Capacity();for(reload=0;reload<2;reload++){for(i=0;i<11;i++)NullStage(reload,i);Failed("weight \"plain\" return 42;\n#unknown",reload,0,0);Failed("weight \"plain\" return #unknown\n42;",reload,0,0);Failed("weight \"plain\" return 42;\n#include \"one.c\"",reload,1,0);Failed("weight \"plain\" return 42;\n#include \"one.c\"",reload,2,0);Failed("weight \"first\" return 42; weight \"unfinished\"",reload,0,0);Failed("weight \"tree\" switch (1) { case 5: invalid }",reload,0,0);Failed("weight \"tree\" switch (1) { case 5: return 6; default: return 9; default: return 11; }",reload,0,0);}Failed("weight \"plain\" return 42;\n#unknown",0,0,1);Attempt(nativeText);Check(!ReadWeightConfig(NULL)&&!ReadWeightConfig("")&&!requests&&!opens&&errors==2,"invalid filename rejects before cache/imports");Finish();puts("Real weight parser cache publication, nullable-stage rollback and native fuzzy values passed (issue #48)");}return 0;}
