/* Actual goal setup, complete item factory/parser and native allocation owners. */
#define main ItemConfigFixtureMain
#include "bot_item_config_regression.c"
#undef main
#ifdef MEMORYMANEGER
extern int numblocks,allocatedmemory,totalmemorysize;
#endif
static void GoalBegin(void){Begin();Check(!itemconfig,"prior goal configuration released");g_gametype=0;droppedweight=NULL;}
static void GoalEnd(void){if(itemconfig)FreeMemory(itemconfig);itemconfig=NULL;droppedweight=NULL;g_gametype=0;End();
#ifdef MEMORYMANEGER
Check(!numblocks&&!allocatedmemory&&!totalmemorysize,"all native tracked logical goal owners release");
#endif
}
static void PreparePrior(int occupied){GoalBegin();if(occupied){itemconfig=LoadItemConfig("prior.c");Values(itemconfig);droppedweight=LibVar("priorweight","777");Check(droppedweight!=NULL,"complete distinct prior native weight");g_gametype=7;Attempt(nativeText);}}
static void GoalNullable(int occupied,int fault){itemconfig_t *prior,header;iteminfo_t saved;libvar_t *weight;int type,baseline,arena;PreparePrior(occupied);prior=itemconfig;if(prior){header=*prior;saved=prior->iteminfo[0];}weight=droppedweight;type=g_gametype;baseline=heapLive;arena=hunkLive;failAt=fault;Check(BotSetupGoalAI()!=BLERR_NOERROR&&requests==failAt&&errors==1&&!opens&&closes==0&&itemconfig==prior&&g_gametype==type&&droppedweight==weight&&hunkLive==arena&&heapLive==baseline+2*((fault-1)/2),"nullable game/config/weight imports reject before file/hunk publication with complete prior goal references");if(prior)Check(!memcmp(&header,prior,sizeof(header))&&!memcmp(&saved,prior->iteminfo,sizeof(saved)),"nullable goal setup preserves every prior item byte");Attempt(nativeText);Check(BotSetupGoalAI()==BLERR_NOERROR&&g_gametype==0&&droppedweight&&droppedweight->value==1000&&itemconfig!=prior&&hunkLive==arena+1,"nullable goal setup retries with complete native default state");Values(itemconfig);GoalEnd();}
static void InvalidType(unsigned int bits){libvar_t *variable;int imports;PreparePrior(1);variable=LibVar("g_gametype","0");Check(variable!=NULL,"invalid game-type cache prepares");variable->value=Opaque(bits);imports=requests;Check(BotSetupGoalAI()==BLERR_LIBRARYNOTSETUP&&requests==imports&&!opens&&itemconfig&&g_gametype==7&&droppedweight&&droppedweight->value==777&&errors==1&&hunkLive==1,"nonfinite/oversized game type rejects before cast/later imports and retains native prior state");Values(itemconfig);GoalEnd();}

static void GoalMalformed(const char *text){itemconfig_t *prior,header;iteminfo_t saved;libvar_t *weight;int baseline;PreparePrior(1);prior=itemconfig;header=*prior;saved=prior->iteminfo[0];weight=droppedweight;Check(LibVar("g_gametype","2.75")&&LibVar("itemconfig","items.c")&&LibVar("droppedweight","1000"),"all complete private goal setup references prepare");baseline=heapLive;Attempt(text);Check(BotSetupGoalAI()==BLERR_CANNOTLOADITEMCONFIG&&itemconfig==prior&&g_gametype==7&&droppedweight==weight&&heapLive==baseline&&hunkLive==1&&!numtokens&&errors>0&&!messages&&opens==1&&closes==1&&!memcmp(&header,prior,sizeof(header))&&!memcmp(&saved,prior->iteminfo,sizeof(saved)),"failed item parser retains every prior goal reference/value/payload and no extra hunk");Attempt(nativeText);Check(BotSetupGoalAI()==BLERR_NOERROR&&itemconfig!=prior&&g_gametype==2&&droppedweight!=weight&&droppedweight->value==1000&&hunkLive==2,"failed goal parser retries with complete configured type/default weight");Values(itemconfig);GoalEnd();}
static void WeightFailure(int fault){itemconfig_t *prior,header;iteminfo_t saved;libvar_t *weight;int baseline;PreparePrior(1);prior=itemconfig;header=*prior;saved=prior->iteminfo[0];weight=droppedweight;Check(LibVar("g_gametype","2.75")&&LibVar("itemconfig","items.c"),"complete native type/config caches prepare before isolated weight import");baseline=heapLive;Attempt(nativeText);failAt=fault;Check(BotSetupGoalAI()==BLERR_LIBRARYNOTSETUP&&requests==fault&&!opens&&itemconfig==prior&&g_gametype==7&&droppedweight==weight&&heapLive==baseline&&hunkLive==1&&!memcmp(&header,prior,sizeof(header))&&!memcmp(&saved,prior->iteminfo,sizeof(saved)),"isolated nullable weight factory rejects before hunk/parser/prior goal publication");GoalEnd();}
static void GoalGolden(void){int baseline;GoalBegin();Check(BotSetupGoalAI()==BLERR_NOERROR&&g_gametype==0&&droppedweight&&droppedweight->value==1000&&heapLive==8&&hunkLive==1&&!errors&&!warnings&&messages==1&&opens==1&&closes==1&&!numtokens,"actual native goal setup defaults/shared ownership");Values(itemconfig);baseline=heapLive;LibVarSet("g_gametype","2.75");LibVarSet("itemconfig","custom.c");LibVarSet("droppedweight","777");Attempt(nativeText);Check(BotSetupGoalAI()==BLERR_NOERROR&&g_gametype==2&&droppedweight->value==777&&heapLive==baseline&&hunkLive==2&&!errors&&!warnings&&messages==1&&opens==1&&closes==1,"complete configured native goal replacement and fractional type truncation");Values(itemconfig);GoalEnd();}
static void NativeFirstGolden(void){GoalBegin();Check(BotSetupGoalAI()==BLERR_NOERROR&&g_gametype==0&&droppedweight&&droppedweight->value==1000&&heapLive==8&&hunkLive==1&&!errors&&!warnings&&messages==1&&opens==1&&closes==1&&!numtokens,"unchanged original native first goal setup golden");Values(itemconfig);GoalEnd();}
int main(int argc,char **argv){int occupied,fault,i;if(argc>1){i=atoi(argv[1]);if(i<12)GoalNullable(i/6,i%6+1);else if(i==12)InvalidType(0x7fc00000U);else if(i==13)GoalMalformed("iteminfo");else if(i==14)WeightFailure(1);else if(i==15)WeightFailure(2);else if(i==16)NativeFirstGolden();else GoalGolden();return 0;}for(occupied=0;occupied<2;occupied++)for(fault=1;fault<=6;fault++)GoalNullable(occupied,fault);InvalidType(0x7fc00000U);InvalidType(0x7f800000U);InvalidType(0xff800000U);InvalidType(0x4f000000U);InvalidType(0xcf800000U);GoalMalformed("iteminfo");{char text[1024];snprintf(text,sizeof(text),"%s#unknown",nativeText);GoalMalformed(text);}WeightFailure(1);WeightFailure(2);GoalGolden();puts("Actual goal setup staged nullable refs/counts/parser, prior payload rollback and physical native ownership passed (issue #48)");return 0;}
