/* Actual public/cached skill inputs with native clamps, fallback and preserved owners. */
#define main CharacterFixtureMain
#include "bot_character_regression.c"
#undef main
#include <float.h>
#include <limits.h>
#define CHARACTER_BYTES (sizeof(bot_character_t)+MAX_CHARACTERISTICS*sizeof(bot_characteristic_t))
static bot_character_t *registry[MAX_CLIENTS+1];
static unsigned char snapshots[MAX_CLIENTS+1][CHARACTER_BYTES];
static const char *skills="skill 1 { 0 1.25 1 11 79 \"one\" } skill 4 { 0 7.25 1 44 79 \"four\" } skill 5 { 0 9.25 1 55 79 \"five\" }";
static float SkillBits(unsigned int bits){float value;memcpy(&value,&bits,sizeof(value));return value;}
static void SkillDone(void){BotShutdownCharacters();LibVarDeAllocAll();Check(!liveOwners&&!numtokens,"all public skill/source/character/string owners physically release");}
static void SkillSnapshot(void){int i;memcpy(registry,botcharacters,sizeof(registry));for(i=1;i<=MAX_CLIENTS;i++)if(botcharacters[i])memcpy(snapshots[i],botcharacters[i],CHARACTER_BYTES);}
static void SkillUnchanged(void){int i;Check(!memcmp(registry,botcharacters,sizeof(registry)),"rejected skill preserves exact occupied/free handles");for(i=1;i<=MAX_CLIENTS;i++)if(botcharacters[i])Check(!memcmp(snapshots[i],botcharacters[i],CHARACTER_BYTES)&&!strcmp(botcharacters[i]->c[79].value.string,botcharacters[i]->skill==1?"one":botcharacters[i]->skill==4?"four":botcharacters[i]->skill==5?"five":"one"),"rejected skill preserves every cached header/field/string owner");}
static void SkillRejected(unsigned int bits,int method,int existing){int before,beforeOwners,beforeOpens,beforeCloses,handle;float skill=SkillBits(bits);Reset(skills);if(existing){Check(BotLoadCharacter("bots/native.c",2.5f)>0,"real interpolated cached registry prepares");SkillSnapshot();}else SkillSnapshot();before=requests;beforeOwners=liveOwners;beforeOpens=opens;beforeCloses=closes;errors=0;handle=method?BotLoadCachedCharacter("bots/native.c",skill,method==2):BotLoadCharacter("bots/native.c",skill);Check(!handle&&errors==1,"invalid skill rejects before character/fallback/interpolation publication");Check(requests==before&&liveOwners==beforeOwners&&opens==beforeOpens&&closes==beforeCloses&&!numtokens,"invalid skill performs no VFS/heap imports or owner release");SkillUnchanged();SkillDone();}
static void PublicGolden(float input,float normalized){int handle,before,beforeOpens;bot_character_t *ch;Reset(skills);handle=BotLoadCharacter("bots/native.c",input);Check(handle>0&&!errors,"native valid/clamped requested skill loads");ch=botcharacters[handle];Check(ch&&ch->skill==normalized&&ch->c[0].type==CT_FLOAT&&fabsf(ch->c[0].value._float-(1.25f+2.0f*(normalized-1.0f)))<0.000001f&&ch->c[1].type==CT_INTEGER&&ch->c[1].value.integer==(normalized<4?11:normalized<5?44:55)&&!strcmp(ch->c[79].value.string,normalized<4?"one":normalized<5?"four":"five"),"native clamp/cohort/interpolation numeric/string fields retain values");before=requests;beforeOpens=opens;Check(BotLoadCharacter("bots/native.c",input)==handle&&requests==before&&opens==beforeOpens&&!errors,"normalized requested skill retains allocation-free cache reuse");SkillDone();}
static void CachedGolden(float skill,int expectedSkill){int handle,before;Reset(skills);handle=BotLoadCachedCharacter("bots/native.c",skill,0);Check(handle==1&&botcharacters[handle]->skill==expectedSkill&&!errors&&!numtokens,"native cached rounding/any-skill fallback retains first handle and loaded skill");if(skill==1||skill==4||skill==5){before=requests;Check(BotLoadCachedCharacter("bots/native.c",skill,0)==handle&&requests==before,"ordinary exact cached skill performs no new imports");}SkillDone();}
static void Ordinary(void){int i;for(i=-4;i<=24;i++){float input=i*0.25f,normalized=input<1?1:input>5?5:input;PublicGolden(input,normalized);}PublicGolden(-FLT_MAX,1);PublicGolden(FLT_MAX,5);PublicGolden(SkillBits(0xff800000u),1);PublicGolden(SkillBits(0x7f800000u),5);PublicGolden(-0.0f,1);CachedGolden(1,1);CachedGolden(4,4);CachedGolden(5,5);CachedGolden(3.49f,1);CachedGolden(3.5f,4);CachedGolden(-1,1);CachedGolden(-2147483648.0f,1);CachedGolden(2147483520.0f,1);}
int main(int argc,char **argv){if(argc>1){int proof=atoi(argv[1]);if(proof==0)SkillRejected(0x7fc00001u,0,0);else if(proof==1)SkillRejected(0x7fc00001u,0,1);else if(proof==2)SkillRejected(0x7fc00001u,1,0);else if(proof==3)SkillRejected(0x7f800000u,1,0);else if(proof==4)SkillRejected(0xff800000u,1,0);else if(proof==5)SkillRejected(0x7f7fffffu,1,0);else if(proof==6)SkillRejected(0xff7fffffu,1,0);else Ordinary();}else{int existing,method;Ordinary();for(existing=0;existing<2;existing++)for(method=0;method<3;method++){SkillRejected(0x7fc00001u,method,existing);SkillRejected(0xffc00001u,method,existing);if(method){SkillRejected(0x7f800000u,method,existing);SkillRejected(0xff800000u,method,existing);SkillRejected(0x7f7fffffu,method,existing);SkillRejected(0xff7fffffu,method,existing);}}puts("Real requested/cached skill guards, native clamps/fallback and unchanged registry owners passed (issue #48)");}return 0;}
