/* Actual staged macro definitions, replacement rollback and external factories. */
#define Q3_EVAL_ENTRY EvalFixtureMain
#include "bot_eval_regression.c"
extern int PC_Directive_define(source_t *);
extern define_t *PC_DefineFromString(char *);
extern define_t *PC_FindHashedDefine(define_t **,char *);
extern void PC_FreeDefine(define_t *);
static unsigned char hashSnapshot[1024*sizeof(define_t *)],headerSnapshot[sizeof(define_t)+16],tokenSnapshot[sizeof(token_t)];
static const char *functionBody="NEW(a,b) a + b\nnext";
static source_t *DefineStart(const char *body,int occupied){source_t *source=EvalStart(body);if(occupied){define_t *prior;Check(PC_AddDefine(source,"OLD 42"),"complete actual prior definition prepares");prior=PC_FindHashedDefine(source->definehash,"OLD");Check(prior&&prior->tokens&&prior->tokens->intvalue==42&&liveOwners==6&&numtokens==1,"native old definition/source physical owners");memcpy(hashSnapshot,source->definehash,sizeof(hashSnapshot));memcpy(headerSnapshot,prior,sizeof(define_t)+4);memcpy(tokenSnapshot,prior->tokens,sizeof(token_t));}return source;}
static void DefinePrior(source_t *source,define_t *prior,int occupied){Check(!memcmp(hashSnapshot,source->definehash,sizeof(hashSnapshot)),"complete hash dictionary remains unchanged after failed definition");if(occupied)Check(PC_FindHashedDefine(source->definehash,"OLD")==prior&&!memcmp(headerSnapshot,prior,sizeof(define_t)+4)&&!memcmp(tokenSnapshot,prior->tokens,sizeof(token_t)),"complete prior definition/name/token bytes remain on failure");}
static void DefineFailed(const char *body,int occupied){source_t *source=DefineStart(body,occupied);define_t *prior=occupied?PC_FindHashedDefine(source->definehash,"OLD"):NULL;int baseOwners=liveOwners,baseTokens=numtokens;if(!occupied)memcpy(hashSnapshot,source->definehash,sizeof(hashSnapshot));Check(!PC_Directive_define(source)&&errors>0&&PC_SourceHasError(source)&&!fatals,"malformed new/replacement definition rejects");DefinePrior(source,prior,occupied);Check(liveOwners==baseOwners+(source->tokens?1:0)&&numtokens==baseTokens+(source->tokens?1:0),"all partial name/parameter/body owners release while retaining native queue");EvalEnd(source);}
static void DefineImport(int occupied,int position){const char *body=occupied?"OLD(a,b) a + b\nnext":functionBody;source_t *source;define_t *prior;int target,baseOwners,baseTokens,baseRequests;source=DefineStart(body,occupied);baseRequests=requests;Check(PC_Directive_define(source),"healthy actual definition import trace");target=baseRequests+position;Check(target<=requests,"actual definition/header/parameter/body/lookahead import identified");EvalEnd(source);source=DefineStart(body,occupied);prior=occupied?PC_FindHashedDefine(source->definehash,"OLD"):NULL;baseOwners=liveOwners;baseTokens=numtokens;if(!occupied)memcpy(hashSnapshot,source->definehash,sizeof(hashSnapshot));failAt=target;Check(!PC_Directive_define(source)&&requests==target&&errors==1&&fatals==(position!=1)&&PC_SourceHasError(source),"each nullable definition import rejects before cache replacement");DefinePrior(source,prior,occupied);Check(liveOwners==baseOwners&&!source->tokens&&numtokens==baseTokens,"nullable macro imports release every staged physical owner");EvalEnd(source);}
static void DefineExternal(int position){define_t *define;Reset("");fatals=0;failAt=position;define=PC_DefineFromString("NATIVE(a,b) a + b");Check(!define&&!liveOwners&&!numtokens&&requests==position,"nullable external script/dictionary/name/parameter/body import rolls back");failAt=0;define=PC_DefineFromString("NATIVE(a,b) a + b");Check(define&&define->numparms==2,"external definition failure retries");PC_FreeDefine(define);Check(!liveOwners&&!numtokens,"external definition physical cleanup");}
static void DefineExternalBad(const char *body){Reset("");fatals=0;Check(!PC_DefineFromString((char *)body)&&errors>0&&!liveOwners&&!numtokens,"malformed external definition leaves no hashed partial owner");}
static void DefineGolden(void){source_t *source;token_t token;define_t *define;source=EvalStart("#define NATIVE(a,b) a + b\nNATIVE(7,8)\n#define OLD 42\nOLD\n#define OLD(a) 1\nOLD(9)\n#define EMPTY\ntail");Check(PC_ReadToken(source,&token)&&token.intvalue==7&&PC_ReadToken(source,&token)&&!strcmp(token.string,"+")&&PC_ReadToken(source,&token)&&token.intvalue==8,"native function parameter/body expansion");Check(PC_ReadToken(source,&token)&&token.intvalue==42,"native object definition expansion");Check(PC_ReadToken(source,&token)&&token.intvalue==1,"native complete replacement expansion");Check(PC_ReadToken(source,&token)&&!strcmp(token.string,"tail")&&!PC_ReadToken(source,&token)&&!errors&&!fatals&&warnings==1&&PC_FindHashedDefine(source->definehash,"EMPTY")&&!PC_FindHashedDefine(source->definehash,"EMPTY")->tokens,"native empty marker definition and replacement warning/token order");EvalEnd(source);Reset("");define=PC_DefineFromString("NATIVE(a,b) a + b");Check(define&&!strcmp(define->name,"NATIVE")&&define->numparms==2&&define->tokens&&!strcmp(define->tokens->string,"a")&&!errors,"native external macro grammar/body order");PC_FreeDefine(define);Check(!liveOwners&&!numtokens,"native external final owners release");}
static void DefinePreviousParameter(void){source_t *source=EvalStart("#define OLD 42\n#define OLD(OLD) 1\nOLD(9)\ntail");token_t token;Check(PC_ReadToken(source,&token)&&token.intvalue==1&&PC_ReadToken(source,&token)&&!strcmp(token.string,"tail")&&!PC_ReadToken(source,&token)&&!errors&&!fatals&&warnings==1,"replacement parses prior-name parameter as a raw identifier before publication");EvalEnd(source);}
static void DefineParams(int count){char body[8192];int i,length;source_t *source;length=snprintf(body,sizeof(body),"NEW(");for(i=0;i<count;i++)length+=snprintf(body+length,sizeof(body)-length,i?",p%d":"p%d",i);snprintf(body+length,sizeof(body)-length,") 1");source=DefineStart(body,0);if(count==128){Check(PC_Directive_define(source)&&PC_FindHashedDefine(source->definehash,"NEW")->numparms==128,"complete native callable parameter capacity remains");}else{memcpy(hashSnapshot,source->definehash,sizeof(hashSnapshot));Check(!PC_Directive_define(source)&&errors==1&&liveOwners==4&&!numtokens,"unsupported parameter count rejects with complete private rollback");DefinePrior(source,NULL,0);}EvalEnd(source);}
int main(int argc,char **argv){if(argc>1){int proof=atoi(argv[1]);if(proof==0)DefineFailed("NEW(a,a) a",0);else if(proof==1)DefineFailed("OLD(a,a) a",1);else if(proof==2)DefineExternalBad("NATIVE(a,a) a");else if(proof==3)DefineExternalBad("NATIVE NATIVE 42");else if(proof>=4&&proof<=10)DefineImport(0,proof-3);else if(proof>=11&&proof<=17)DefineImport(1,proof-10);else if(proof>=18&&proof<=26)DefineExternal(proof-17);else if(proof==27)DefineFailed("NEW 7 \"unterminated",0);else if(proof==29)DefinePreviousParameter();else DefineGolden();return 0;}DefineGolden();DefinePreviousParameter();{int occupied,position;for(occupied=0;occupied<2;occupied++){const char *name=occupied?"OLD":"NEW";char body[256];snprintf(body,sizeof(body),"%s(a,a) a",name);DefineFailed(body,occupied);snprintf(body,sizeof(body),"%s(a,7) a",name);DefineFailed(body,occupied);snprintf(body,sizeof(body),"%s(a,b",name);DefineFailed(body,occupied);snprintf(body,sizeof(body),"%s ## 7",name);DefineFailed(body,occupied);snprintf(body,sizeof(body),"%s 7 ##",name);DefineFailed(body,occupied);snprintf(body,sizeof(body),"%s %s 7",name,name);DefineFailed(body,occupied);snprintf(body,sizeof(body),"%s 7 \"unterminated",name);DefineFailed(body,occupied);for(position=1;position<=7;position++)DefineImport(occupied,position);}for(position=1;position<=9;position++)DefineExternal(position);}DefineExternalBad("NATIVE(a,a) a");DefineExternalBad("NATIVE NATIVE 42");DefineExternalBad("NATIVE ## 7");DefineParams(128);DefineParams(129);Reset("");Check(!PC_DefineFromString(NULL)&&!PC_DefineFromString("")&&!requests&&!liveOwners&&!numtokens,"missing external definitions reject before imports");puts("Real definition staging, nullable imports, complete prior cache rollback and native macro grammar passed (issue #48)");return 0;}
