/* Actual string getters, complete native padding and rejected buffer capacities. */
#define main CharacterFixtureMain
#include "bot_character_regression.c"
#undef main
#include <limits.h>
#define CHARACTER_BYTES (sizeof(bot_character_t)+MAX_CHARACTERISTICS*sizeof(bot_characteristic_t))
static unsigned char snapshot[CHARACTER_BYTES];
static int imports;
static void StringBegin(void){Reset("skill 4 { 0 42 2 \"native\" 79 \"\" }");botcharacters[1]=BotLoadCharacterFromFile("bots/native.c",4);Check(botcharacters[1]&&liveOwners==3&&!numtokens&&!errors,"real ordinary/empty string characters prepare");imports=requests;memcpy(snapshot,botcharacters[1],CHARACTER_BYTES);}
static void StringEnd(void){Check(requests==imports&&!memcmp(snapshot,botcharacters[1],CHARACTER_BYTES)&&!strcmp(botcharacters[1]->c[2].value.string,"native")&&!botcharacters[1]->c[79].value.string[0],"string getter preserves all character/ordinary/empty owners without imports");BotFreeCharacter2(1);Check(!liveOwners&&!numtokens,"all native string/source/character owners physically release");}
static void Rejected(int size,int nullBuffer){unsigned char bytes[32],saved[32];StringBegin();memset(bytes,0xa5,sizeof(bytes));memcpy(saved,bytes,sizeof(bytes));Characteristic_String(1,2,nullBuffer?NULL:(char *)bytes+8,size);Check(!memcmp(bytes,saved,sizeof(bytes))&&!errors,"missing/nonpositive string output remains unchanged without diagnostics");StringEnd();}
static void Valid(void){unsigned char bytes[1040];int kind,size,i,count=0;StringBegin();for(kind=0;kind<2;kind++)for(size=1;size<=1024;size++){const char *text=kind?"":"native";size_t length=strlen(text);memset(bytes,0xa5,sizeof(bytes));Characteristic_String(1,kind?79:2,(char *)bytes+8,size);for(i=0;i<(int)sizeof(bytes);i++){unsigned char expected=0xa5;if(i>=8&&i<8+size)expected=(i-8<size-1&&(size_t)(i-8)<length)?(unsigned char)text[i-8]:0;Check(bytes[i]==expected,"native copied/truncated/NUL/padding bytes retain exact capacity and canaries");}Check(!errors,"valid native string output has no diagnostic");count++;}Check(count==2048,"all ordinary/empty capacities one through 1024 checked");StringEnd();}
static void Metadata(void){unsigned char bytes[32],saved[32];StringBegin();memset(bytes,0xa5,sizeof(bytes));memcpy(saved,bytes,sizeof(bytes));Characteristic_String(0,2,(char *)bytes+8,16);Characteristic_String(1,80,(char *)bytes+8,16);Characteristic_String(1,0,(char *)bytes+8,16);Check(errors==3&&!memcmp(bytes,saved,sizeof(bytes)),"native handle/index/type rejection preserves complete output");StringEnd();}
int main(int argc,char **argv){if(argc>1){int proof=atoi(argv[1]);if(proof==0)Rejected(0,0);else if(proof==1)Rejected(-1,0);else if(proof==2)Rejected(INT_MIN,0);else if(proof==3)Rejected(16,1);else if(proof==4)Rejected(0,1);else if(proof==5)Rejected(-1,1);else{Valid();Metadata();}}else{Valid();Metadata();Rejected(0,0);Rejected(-1,0);Rejected(INT_MIN,0);Rejected(16,1);Rejected(0,1);Rejected(-1,1);puts("Real characteristic string capacities, rejected buffers and 2048 native padded outputs passed (issue #48)");}return 0;}
