/* Actual public integer getters and original native valid-value comparisons. */
#define main CharacterFixtureMain
#include "bot_character_regression.c"
#undef main
#include <float.h>
#include <limits.h>
#include Q3_INTEGER_NATIVE
#define CHARACTER_BYTES (sizeof(bot_character_t)+MAX_CHARACTERISTICS*sizeof(bot_characteristic_t))
static unsigned char snapshot[CHARACTER_BYTES];
static int imports;
static void IntegerBegin(void){Reset("skill 4 { 0 42 1 1.25 79 \"owned\" }");botcharacters[1]=BotLoadCharacterFromFile("bots/native.c",4);Check(botcharacters[1]&&liveOwners==2&&!numtokens&&!errors,"real parsed integer/float/string character prepares");imports=requests;}
static void IntegerEnd(void){Check(requests==imports&&!memcmp(snapshot,botcharacters[1],CHARACTER_BYTES)&&!strcmp(botcharacters[1]->c[79].value.string,"owned"),"getters preserve complete character and physical string ownership without imports");BotFreeCharacter2(1);Check(!liveOwners&&!numtokens,"all parsed character/source owners physically release");}
static void FloatBits(unsigned int bits){memcpy(&botcharacters[1]->c[1].value._float,&bits,sizeof(bits));}
static void IntegerSnapshot(void){memcpy(snapshot,botcharacters[1],CHARACTER_BYTES);errors=0;}
static void Rejected(unsigned int bits,int bounded){IntegerBegin();FloatBits(bits);IntegerSnapshot();Check((bounded?Characteristic_BInteger(1,1,10,20):Characteristic_Integer(1,1))==0&&errors==1,"unrepresentable/nonfinite conversion rejects with native error fallback");IntegerEnd();}
static void Wide(float value,int min,int max,int expected){IntegerBegin();botcharacters[1]->c[1].value._float=value;IntegerSnapshot();Check(Characteristic_BInteger(1,1,min,max)==expected&&!errors,"finite bounded float clamps before native integer conversion");IntegerEnd();}
static void NativeValues(void){const int bounds[][2]={{INT_MIN,INT_MAX},{-10,10},{0,0},{0,1},{10,20},{-20,-10},{INT_MAX,INT_MAX},{INT_MIN,INT_MIN},{-1,0},{0,INT_MAX},{INT_MIN,0}};int i,j,comparisons=0;IntegerBegin();for(i=-400;i<=400;i++){float value=i*0.25f;botcharacters[1]->c[1].value._float=value;IntegerSnapshot();Check(Characteristic_Integer(1,1)==NativeCharacteristic_Integer(1,1)&&!errors,"valid public integer truncation matches original actual body");comparisons++;for(j=0;j<(int)(sizeof(bounds)/sizeof(bounds[0]));j++){Check(Characteristic_BInteger(1,1,bounds[j][0],bounds[j][1])==NativeCharacteristic_BInteger(1,1,bounds[j][0],bounds[j][1])&&!errors,"valid bounded truncation/clamp matches original actual body");comparisons++;}}botcharacters[1]->c[1].value._float=-0.0f;IntegerSnapshot();Check(Characteristic_Integer(1,1)==0&&!errors,"negative zero retains native integer value");for(i=0;i<3;i++){int values[]={INT_MIN,42,INT_MAX};botcharacters[1]->c[0].value.integer=values[i];IntegerSnapshot();Check(Characteristic_Integer(1,0)==values[i]&&Characteristic_BInteger(1,0,-10,10)==NativeCharacteristic_BInteger(1,0,-10,10)&&!errors,"native integer fields retain complete signed endpoints and bounds");}IntegerSnapshot();Check(Characteristic_Integer(1,79)==0&&errors==1,"native wrong type fallback remains");errors=0;Check(Characteristic_BInteger(1,79,10,20)==10&&errors==1,"native bounded wrong type fallback remains");errors=0;Check(Characteristic_BInteger(1,80,10,20)==10&&errors==1,"native bounded invalid-index fallback remains");errors=0;Check(Characteristic_BInteger(1,1,20,10)==0&&errors==1,"native reversed bounds reject before conversion");IntegerEnd();Check(comparisons==9612,"complete original valid getter corpus compared");}
static void ParsedWide(void){Reset("skill 4 { 79 \"owned\" 1 2147483648.0 }");botcharacters[1]=BotLoadCharacterFromFile("bots/native.c",4);Check(botcharacters[1]&&liveOwners==2&&!numtokens&&!errors,"real lexer parses finite value beyond signed integer range");imports=requests;IntegerSnapshot();Check(Characteristic_Integer(1,1)==0&&errors==1,"actual parsed wide float rejects integer cast");errors=0;Check(Characteristic_BInteger(1,1,INT_MIN,INT_MAX)==INT_MAX&&!errors,"actual parsed wide float safely clamps to full signed bound");IntegerEnd();}
int main(int argc,char **argv){if(argc>1){int proof=atoi(argv[1]);if(proof==0)Rejected(0x7fc00001u,0);else if(proof==1)ParsedWide();else if(proof==2)Rejected(0x7f7fffffu,0);else if(proof==3)Rejected(0xff7fffffu,0);else if(proof==4)Rejected(0x7f800000u,0);else if(proof==5)Rejected(0xff800000u,0);else if(proof==6)Wide(FLT_MAX,10,20,20);else if(proof==7)Wide(-FLT_MAX,-20,-10,-20);else if(proof==8)Rejected(0x7fc00001u,1);else NativeValues();}else{int bounded;NativeValues();ParsedWide();for(bounded=0;bounded<2;bounded++){Rejected(0x7fc00001u,bounded);Rejected(0x7f800000u,bounded);Rejected(0xff800000u,bounded);}Rejected(0x7f7fffffu,0);Rejected(0xff7fffffu,0);Wide(FLT_MAX,10,20,20);Wide(-FLT_MAX,-20,-10,-20);Wide(2147483648.0f,INT_MAX,INT_MAX,INT_MAX);Wide(-2147483648.0f,INT_MIN,INT_MIN,INT_MIN);Wide(2147483520.0f,INT_MIN,INT_MAX,2147483520);puts("Real characteristic integer conversions, bounded clamps and 9612 native value comparisons passed (issue #48)");}return 0;}
