/* Actual float getters, representation-safe bounds and original native comparisons. */
#define main CharacterFixtureMain
#include "bot_character_regression.c"
#undef main
#include <float.h>
#include <limits.h>
#include "bot_character_float_native.h"
#define CHARACTER_BYTES (sizeof(bot_character_t)+MAX_CHARACTERISTICS*sizeof(bot_characteristic_t))
static unsigned char snapshot[CHARACTER_BYTES];
static int imports;
static float BoundBits(unsigned int bits){volatile unsigned int representation=bits;unsigned int actual=representation;float value;memcpy(&value,&actual,sizeof(value));return value;}
static void BoundFieldBits(unsigned int bits){volatile unsigned int representation=bits;unsigned int actual=representation;memcpy(&botcharacters[1]->c[1].value._float,&actual,sizeof(actual));}
static unsigned int ResultBits(float value){unsigned int bits;volatile unsigned int representation;memcpy(&bits,&value,sizeof(bits));representation=bits;return representation;}
static void BoundBegin(void){Reset("skill 4 { 0 42 1 1.25 79 \"owned\" }");botcharacters[1]=BotLoadCharacterFromFile("bots/native.c",4);Check(botcharacters[1]&&liveOwners==2&&!numtokens&&!errors,"real parsed float/integer/string character prepares");imports=requests;}
static void BoundSnapshot(void){memcpy(snapshot,botcharacters[1],CHARACTER_BYTES);errors=0;}
static void BoundEnd(void){Check(requests==imports&&!memcmp(snapshot,botcharacters[1],CHARACTER_BYTES)&&!strcmp(botcharacters[1]->c[79].value.string,"owned"),"float getter preserves complete character/string owners without imports");BotFreeCharacter2(1);Check(!liveOwners&&!numtokens,"all native float/source/character owners physically release");}
static void BadBound(unsigned int bits,int upper){float min=upper?0:BoundBits(bits),max=upper?BoundBits(bits):10;BoundBegin();BoundSnapshot();Check(ResultBits(Characteristic_BFloat(1,1,min,max))==0&&errors==1,"NaN bound rejects with zero/error before output selection");BoundEnd();}
static void BadValue(unsigned int bits,int bounded){BoundBegin();BoundFieldBits(bits);BoundSnapshot();Check(ResultBits(bounded?Characteristic_BFloat(1,1,10,20):Characteristic_Float(1,1))==0&&errors==1,"non-finite characteristic rejects in public/bounded float getter");BoundEnd();}
static void NativeValues(void){float bounds[][2]={{-FLT_MAX,FLT_MAX},{-10,10},{0,0},{0,1},{10,20},{-20,-10},{-1,0},{0,FLT_MAX},{-FLT_MAX,0},{-100,-100},{100,100}};int i,j,count=0;BoundBegin();for(i=-400;i<=400;i++){botcharacters[1]->c[1].value._float=i*0.25f;BoundSnapshot();Check(ResultBits(Characteristic_Float(1,1))==ResultBits(NativeCharacteristic_Float(1,1))&&!errors,"native representable public float bits remain exact");count++;for(j=0;j<(int)(sizeof(bounds)/sizeof(bounds[0]));j++){Check(ResultBits(Characteristic_BFloat(1,1,bounds[j][0],bounds[j][1]))==ResultBits(NativeCharacteristic_BFloat(1,1,bounds[j][0],bounds[j][1]))&&!errors,"native finite bound/clamp result bits remain exact");count++;}}BoundFieldBits(0x80000000u);BoundSnapshot();Check(ResultBits(Characteristic_Float(1,1))==0x80000000u&&!errors,"native negative zero bits remain");for(i=0;i<3;i++){int integers[]={INT_MIN,42,INT_MAX};botcharacters[1]->c[0].value.integer=integers[i];BoundSnapshot();Check(ResultBits(Characteristic_Float(1,0))==ResultBits(NativeCharacteristic_Float(1,0))&&!errors,"native signed integer-to-float values remain");}botcharacters[1]->c[1].value._float=1.25f;BoundSnapshot();Check(Characteristic_BFloat(1,79,10,20)==10&&errors==1,"native bounded wrong type fallback remains");errors=0;Check(Characteristic_BFloat(1,80,10,20)==10&&errors==1,"native bounded invalid index fallback remains");errors=0;Check(ResultBits(Characteristic_BFloat(1,1,20,10))==0&&errors==1,"native reversed bounds reject");BoundEnd();Check(count==9612,"complete original float getter corpus compared");}
static void InfinityBounds(void){float infinity=BoundBits(0x7f800000u),negative=BoundBits(0xff800000u);float bounds[5][2]={{negative,infinity},{negative,0},{0,infinity},{infinity,infinity},{negative,negative}};int i;BoundBegin();BoundSnapshot();for(i=0;i<5;i++)Check(ResultBits(Characteristic_BFloat(1,1,bounds[i][0],bounds[i][1]))==ResultBits(NativeCharacteristic_BFloat(1,1,bounds[i][0],bounds[i][1]))&&!errors,"defined native signed infinity bound semantics remain exact");BoundEnd();}
int main(int argc,char **argv){if(argc>1){int proof=atoi(argv[1]);if(proof<2)BadBound(0x7fc00001u,proof);else if(proof<5){unsigned int bits[]={0x7fc00001u,0x7f800000u,0xff800000u};BadValue(bits[proof-2],0);}else if(proof<8){unsigned int bits[]={0x7fc00001u,0x7f800000u,0xff800000u};BadValue(bits[proof-5],1);}else{NativeValues();InfinityBounds();}}else{int upper,bounded;NativeValues();InfinityBounds();for(upper=0;upper<2;upper++){BadBound(0x7fc00001u,upper);BadBound(0xffc00001u,upper);}for(bounded=0;bounded<2;bounded++){BadValue(0x7fc00001u,bounded);BadValue(0xffc00001u,bounded);BadValue(0x7f800000u,bounded);BadValue(0xff800000u,bounded);}puts("Real float getters, NaN guards, infinity bounds and 9612 native result bits passed (issue #48)");}return 0;}
